cockpit-project/cockpit-podman

- Makefile
> Bump Cockpit test API to 172

- src/Containers.jsx
- src/Images.jsx
- src/app.jsx
> change JSON.parse  to object type

- HACKING.md
- package.json
Document this command in HACKING.md file
> Allow running eslint with `npm run eslint`

- src/ContainerCommitModal.jsx
- src/podman.scss
Replace `<form/> `with `<FormGroup/>` inside `<Form/>`, otherwise there will be a warning.
> Replace <form/> with <FormGroup/> inside <Form/>

- src/ContainerDetails.jsx
- src/ImageRunModal.jsx
- test/check-application
> Add publishing ports option to the run image dialog

- lib/cockpit-components-file-autocomplete.css
- lib/cockpit-components-file-autocomplete.jsx
- package.json
- src/ImageRunModal.jsx
- src/podman.scss
- test/check-application
> Add volumes to the run image dialog

- lib/cockpit-components-select.jsx
- lib/page.css
- test/check-application
This makes them keyboard accessible. See
https://github.com/cockpit-project/cockpit/pull/11155 for details.
> Sync cockpit Select component with upstream

- Makefile
- lib/cockpit-components-file-autocomplete.jsx
number tests succeeded: 6
failures: 1, on clicking run which would indicate a podman error
> Flake fixes

- cockpit-podman.spec.in
- src/ContainerCommitModal.jsx
- src/Containers.jsx
- src/ImageRunModal.jsx
- src/Images.jsx
- src/app.jsx
- src/util.js
- src/varlink.js
- test/check-application
Blocked till libpod release v1.1.3 https://github.com/containers/libpod/releases
> Use podman events to trigger state updates

- package.json
Check for any outstanding update of point version of any outstanding NPM package dependency
> package.json: Update node-sass package dependency

- cockpit-podman.spec.in
- src/ContainerCommitModal.jsx
- src/varlink.js
I have included the 'drop epoch' commit as well, so that we can test how this behaves on rhel-8-1
> Handle properly more response calls

- package.json
- src/ContainerTerminal.jsx
I was not able to push into #144 so I am reopening this with a fix.
> Update to a new xterm

- lib/listing.less
- lib/page.css
- lib/variables.less
- src/ContainerDetails.jsx
- src/ContainerHeader.jsx
- src/Containers.jsx
- src/ImageDetails.jsx
- src/ImageRunModal.jsx
- src/ImageSearchModal.css
- src/ImageSearchModal.jsx
- src/Images.jsx
- src/podman.scss
- test/check-application
This addresses _most_ of the PF4ish related issues with Cockpit-Podman.
Known outstanding issues:
Please test this out and add more issues you might find.
> Pf4ish fix

- packit.yaml
See <https://packit.dev>. This will gradually replace our cockpituous
configuration.
> Add packit configuration

- lib/form-layout.less
- src/ContainerCommitModal.jsx
- src/ImageRunModal.jsx
- src/podman.scss
Cockpit itself changed to `ct-form` recently; this syncs the name change with Cockpit-Podman.
> Rename ct-form-layout to ct-form

- src/Containers.jsx
- src/Images.jsx
- src/app.jsx
Getting containers takes a bit (even a few seconds for me). While it gets loaded it shows `No containers` which is confusing since they are not yet loaded. With this PR it shows firstly `Loading containers...`.
> Show loading state while getting containers/images

- src/ImageRunModal.jsx
- test/check-application
This was never finished due to bug in podman.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1732713
> Enable setting up memory

- package.json
See https://github.com/less/less.js/issues/3414
> package.json: Bump up version on less-loader

- test/check-application
Blocks https://github.com/cockpit-project/cockpit/pull/12641
> Tests tweaks

- lib/cockpit-components-listing.jsx
- lib/cockpit-components-select.jsx
- lib/form-layout.less
- lib/listing.less
- src/podman.scss
- test/check-application
@garrett can I get your review and help please?
We cannot switch to two columns, see the tmp commit. But then the buttons are not align, see:
Also other visual change is that `Get new image` is aligned bit differently, is this correct? Otherwise there are not obvious changes.
> Port libs from Cockpit

- src/ContainerCommitModal.jsx
- src/ContainerDetails.jsx
- src/ContainerTerminal.jsx
- src/Containers.jsx
- src/ImageDetails.jsx
- src/ImageRunModal.jsx
- src/ImageSearchModal.jsx
- src/Images.jsx
- src/app.jsx
- src/util.js
Picked from #173 so there are less changes and easier to review.
> Changes for user containers

- Makefile
I mostly miss the `-l` option :)
> Bump version of test/common

- package.json
- po/de.po
I was not able to push into #232
> Update po + workaround for broken npm module

- Makefile
- po/de.po
- po/manifest2po
- po/sk.po
> Update to new zanata cli

- po/cs.po
Update translations from Fedora Zanata
> Update translations from Fedora Zanata

- src/index.html
See https://www.patternfly.org/v4/documentation/overview/red-hat-font
> Adopt the CSS changes that introduce the Red Hat font into PatternFly

- package.json
Check for any outstanding update of point version of any outstanding NPM package dependency
> package.json: Update bootstrap package dependency

- .gitignore
- Makefile
- po/cs.po
- po/de.po
- po/pt_PT.po
- po/sk.po
- po/tr.po
- po/uk.po
- po/zanata.xml
- po/zh_CN.po
This needs to do successful po-refresh. But before I trigger it, I want to get review.
I did one refresh:
1. It pushed [this commit](https://github.com/marusak/cockpit-podman-weblate/commit/864ab0cd34df1065e78bed564220d55549831dfe) updating `.pot` file
2. Created [refresh](https://github.com/cockpit-project/cockpit-podman/pull/279) (it contains two more commits, but the point is that it picked new language (Turkish), ignored French (as it has only 11% translated strings) and there was no update in already existing languages. (I'll do some change in Slovak so we have also normal update)
> po: Switch from Zanata to Weblate

- po/cs.po
- po/pl.po
- po/pt_PT.po
- po/sk.po
- po/tr.po
Update translations from Fedora Weblate
> Update translations from Fedora Weblate

- src/ContainerLogs.jsx
- src/ContainerTerminal.jsx
- src/Containers.jsx
- test/check-application
> Show historical logs

- src/app.jsx
We correctly use moment to format dates and times, but we never set
language.
> Localize dates and times

- package.json
Check for any outstanding update of point version of any outstanding NPM package dependency
> package.json: Update xterm package dependency

- Makefile
- test/check-application
Use recent Cockpit standard test API to handle the directory
restoration.
Clean up/restore user state as well.
> test: Make tests non-destructive

- Makefile
> Makefile: Call run-tests in make check target

- src/app.jsx
- test/check-application
Carried over from https://github.com/cockpit-project/cockpit-podman/pull/377
> Check if root user and skip user service if true

- src/ImageRunModal.jsx
- test/check-application
Fixes #362
Resolves rhbz#1811773
Locally `TestApplication.testRunImageUser` is failing, but having hard time to find an actual reproducer. Here is what I am trying: [reportfull.txt](https://github.com/cockpit-project/cockpit-podman/files/4931590/reportfull.txt)
> Enable setting up selinux label on mounted volumes

- src/app.jsx
- src/client.js
- src/rest.js
- test/check-application
> Dynamically update cpu and memory info

- lib/cockpit-components-listing-panel.scss
- lib/cockpit-components-select.jsx
- lib/form-layout.scss
- lib/listing.scss
- lib/page.scss
- lib/variables.scss
Fixes #410
Haven't noticed any visual changes, except that #410 is now fixed :)
> lib: Sync with current cockpit

- src/ContainerDetails.jsx
- src/Containers.jsx
- src/app.jsx
- src/client.js
- test/check-application
Showing network info by inspecting a container, also changed some logic in `app.jsx`, here is what in my mind:
```
pageload:
getAllContainers
if running: stream stats
inpect every container(background) -> detail(inspected data)
event - create,start,die...:
updateContainerState
if running: updateStats, detail
otherwise: delete stats, detail
event - remove,cleanup...:
getAllContainers
cleanup works on exited container, thus no need to care about containerDetail, cause it will be deleted on `die` event.
```
> Add network info

- src/ContainerHeader.jsx
- src/Containers.jsx
- src/Images.jsx
- src/app.jsx
- src/podman.scss
- test/check-application
> Filter page by user/system

- src/ImageSearchModal.jsx
> Add spaces to radios in image search modal

- src/ContainerTerminal.jsx
- src/Containers.jsx
- src/client.js
- test/check-application
> If container does not have tty, 'exec' and then connect

- src/ImageSearchModal.css
- src/ImageSearchModal.jsx
- src/Images.jsx
- src/app.jsx
- src/client.js
- src/podman.scss
- test/check-application
Enables users to select which registry should be used.
Part of #85 (the other part is managing these registries).
No tests yet, I'll write them now, but wanted to ask @garrett what he thinks about this design.
> Enable selecting registries

- src/ImageDeleteModal.jsx
- src/Images.css
- src/Images.jsx
- src/client.js
- test/check-application
> Enable untagging images

- test/check-application
criu is not in Debian testing, and will not be for a while:
https://bugs.debian.org/796536
Ensure that the UI shows a proper error message there.
> test: Adjust checkpoint tests for debian-testing

- src/Containers.jsx
- src/ImageUsedBy.jsx
- src/app.jsx
- test/check-application
This got broken with commit b91d6906
> Fix showing 'n/a' on stats when on CGroupsV1

- lib/table.css
- src/Containers.jsx
- src/PodActions.jsx
- src/client.js
- src/util.js
- test/check-application
> Add actions for Pods

- test/check-application
This command sometimes fails in CI, I cannot reproduce locally but thought that maybe this could help?
> test: Get input and output for 'dd' from container

- package.json
> package.json: Cleanup unneeded dependencies

- src/ImageDeleteModal.jsx
- test/check-application
I have no idea how it worked before...
> Dowload test fixes

- po/cs.po
- po/de.po
- po/es.po
- po/fr.po
- po/pl.po
- po/pt_BR.po
- po/pt_PT.po
- po/sk.po
- po/tr.po
- po/uk.po
- po/zh_CN.po
There has been issue with weblate not syncing pot files properly, so I want to test it out.
> Refresh translations from weblate

- src/ContainerLogs.jsx
- src/ContainerTerminal.jsx
- src/ImageSearchModal.jsx
- src/app.jsx
- src/client.js
For now we want to use one version but we already were inconsistent.
> Extract API version into client

- test/check-application
> test: Wait longer until container is checkpoint-ed

- Makefile
One more remaining reminder of fedora-31 :)
> Makefile: Bump default OS to fedora-32

- package.json
Check for any outstanding update of point version of any outstanding NPM package dependency
> npm update xterm

- Makefile
- test/check-application
- test/run
If `make check` failed but `make po` succeeded we would return success.
> test: Fail when `make check` fails

- .travis.yml
- Makefile
- test/check-application
cockpit-podman is in Ubuntu now, so let's make sure it stays working.
> Add testing on ubuntu-stable

- test/check-application
- test/vm.install
Docker now has strict limits for how much we can pull from it. Lets use
something different.
> Replace docker.io with quay.io

- test/check-application
- test/vm.install
…ase 231"
This reverts commit 75a9eb08dd3770782529a08f801609e2df907754.
It was meant to be a temporary workaround anyway.
> Remove test workaround for the limited access modals

- lib/cockpit-components-empty-state.css
- lib/cockpit-components-empty-state.jsx
- src/ContainerLogs.jsx
- src/ContainerTerminal.css
- src/ContainerTerminal.jsx
- src/Containers.jsx
- src/ImageRunModal.jsx
- src/ImageSearchModal.css
- src/ImageSearchModal.jsx
- test/check-application
(most likely breaks tests so I'll let it run, then fix tests and repush also with closes)
Before: (Searching)
After:
Before: (Not found)
After:
Before: (when you open the dialog)
After:
Before: (terminal/logs)
After:
> Empty states improvements

- test/check-application
I wonder who introduced this :thinking:
> test: Drop forgotten sit()

- Makefile
- packit.yaml
- test/check-application
I just want to run `fedora-33/rawhide` but though why not fixing this? :)
> Packit fixes

- src/ImageRunModal.jsx
> Show correct selected option for selinux in UI

- Makefile
- test/check-application
- test/vm.install
These things should work, but maybe in some older version we still need them or maybe it discovers some other issues.
> A bit of tests cleanup

- .github/workflows/livetest.yml
Cherry-picked from starter-kit commit 6f04071d.
>  Introduce a github action which builds a cockpit preview when requested

- Makefile
Testing (and possibly fixing) fedora-34
> Makefile: Bump test/common and pkg/lib to 239

- test/check-application
I noticed these while investigating the failures on rhel-9-0.
> Small test cleanups

- Makefile
- test/check-application
This got a UI overhaul recently, so just our tests accordingly.
> test: update expected strings in sudo prompt

- test/check-application
I am having hard time reproducing issues that CI has locally, thus I'll try this PR.
Starting simple.
> test: test

- src/ImageDetails.jsx
- src/ImageRunModal.jsx
- src/Images.css
- src/Images.jsx
- src/podman.scss
- test/check-application
Part of the cockpit-podman redesign https://github.com/cockpit-project/cockpit/discussions/16059
> Redesign images overview

- src/ContainerDetails.jsx
- src/podman.scss
I've kept the commits separate, for easier reviewing. Between the git commit line and the comments in-file, I hope they're self-explanatory enough.
> Container card redesign follow-ups

- Makefile
> Bump up cockpit libraries

- src/ContainerCommitModal.jsx
- src/ImageSearchModal.css
- src/Images.css
- src/PodActions.jsx
- src/PodActions.scss
- src/app.jsx
- src/podman.scss
> Css cleanup

- src/ImageRunModal.jsx
The sm breakpoint is too late for switching to the horizontal layout.
This is still not ideal but it makes it more usable.
> Change the breakpoint to md for the integration tab

- src/ContainerCommitModal.jsx
- src/ContainerRestoreModal.jsx
- src/Containers.jsx
- test/check-application
> Commit modal improvements and bug fixes

- test/check-application
Let's make this string formatting method the only one to use from now
on.
These files were autoconverted with flynt.
> tests: autoconvert all python string formatting to fstring

- src/ImageRunModal.jsx
> Use form classes for tabs, not grid

- webpack.config.js
Fixes #855
Cherry-picked from starter-kit commit db6397050a92
> webpack: Drop unused import

- src/PodActions.jsx
Make the pod actions more consistent with the conainer actions.
> Update pod actions

- test/check-application
Needs to land in lockstep with the image refresh in https://github.com/cockpit-project/bots/pull/2741
> test: Debian testing now has container restart capability

- src/Containers.jsx
> Move pod status left of actions

- package.json
This reverts commit 14d93495a6c52ac59806d996d4600b0630406a25 due to https://github.com/patternfly/patternfly-react/issues/6741
> Revert the latest patternfly update

- src/PruneUnusedImagesModal.jsx
> Make possible to translate strings

- src/Containers.jsx
- src/ImageRunModal.jsx
- test/check-application
---
When a local image `fedora:latest` is available but a newer version is available on the image registry, checking the "pull latest image" checkbox will pull the latest version before creating the new container
> Add always fetch latest version

- Makefile
Now assert_pixels will also check the mobile layout.
> test: Update to reworked pixel test machinery

- Makefile
New pixels: https://github.com/cockpit-project/pixel-test-reference/compare/e45318da3c227623af5062326fab086d87f7e9cd..44585b3d10aebacd9d543c3efbb72e4d77102e32
> test: Update test/common for "medium" browser layout

- HACKING.md
- README.md
Adopt the recent doc improvements from https://github.com/cockpit-project/cockpit-machines/pull/550
> Update install and test instructions

- test/browser/browser.sh
See https://tmt.readthedocs.io/en/stable/overview.html#variables
---
Initially draft, as I broke a test to validate artifacts.
> fmf: Use official TMT test data directory for artifacts

- Makefile
- src/ContainerDetails.jsx
- src/podman.scss
- webpack.config.js
Cherry picked from https://github.com/cockpit-project/cockpit-podman/pull/897
> Small improvements

- cockpituous-release
Point 13 on https://fedorapeople.org/groups/schedule/f-36/f-36-key-tasks.html
> cockpituous: Enable bodhi for Fedora 36

- Makefile
- test/check-application
- test/vm.install
- https://github.com/cockpit-project/bots/pull/3331
> Add testing on fedora-coreos

- src/ContainerDeleteModal.jsx
- src/ForceRemoveModal.jsx
- src/ImageSearchModal.jsx
- src/PodActions.jsx
> warning dialogs: remove "Please"

- src/util.js
- test/check-application
https://logs.cockpit-project.org/logs/pull-950-20220517-155040-1aeddd81-fedora-36-devel/Coverage/src/index.html
> Coverage discovered fixes

- test/check-application
fedora-coreos contains two additional images - cockpit/ws and intermediate one.
> test: Adjust tests for coreos

- src/app.jsx
This cuts down on the horizontal padding on small devices using Cockpit's `ct-pagesection-mobile` class for `PageSection`.
> mobile: Drop the gutter in small sizes

- Makefile
> Makefile: Update default OS and cockpit checkout

- src/ContainerLogs.jsx
- src/Containers.jsx
- test/check-application
> Reconnect to logs when container starts

- src/Images.jsx
- test/check-application
The internal columns change content and also shift around when the
images change.
> test: Ignore most pixels in the Images table

- src/ImageRunModal.jsx
- src/ImageRunModal.scss
- test/check-application
> Use NumberInput for Image Run Dialog

- src/ContainerCheckpointModal.jsx
- src/ContainerCommitModal.jsx
- src/ContainerDeleteModal.jsx
- src/ContainerRenameModal.jsx
- src/ContainerRestoreModal.jsx
- src/Containers.jsx
- src/ForceRemoveModal.jsx
- src/ImageDeleteModal.jsx
- src/ImageRunModal.jsx
- src/ImageSearchModal.jsx
- src/Images.jsx
- src/PodActions.jsx
- src/app.jsx
This also makes sure that the dropdowns are closed after selecting an
action from them.  This was a bit inconsistent.
Also, the error in the PodDeleteModal is now outside of the container
Stack element.  Deleting a empty pod would never shown an error.
> all: Use WithDialogs protocol

- .stylelintrc.json
- HACKING.md
- package.json
- src/ImageRunModal.scss
- src/ImageSearchModal.css
- src/Images.css
- src/podman.scss
- webpack.config.js
See https://github.com/cockpit-project/starter-kit/pull/595
> Add stylelint to cockpit-podman

- test/check-application
See https://github.com/cockpit-project/bots/pull/3641
---
Needs to land in lockstep with https://github.com/cockpit-project/bots/pull/3641
> test: Adjust for ubuntu-stable moving to 22.10 "kinetic"

- Makefile
- packit.yaml
Broken out from PR #1016, which has been blocked for a while.
> two simple cleanups

- src/Containers.jsx
- test/check-application
> Do not show intermediate images in create container dialog

- src/ContainerIntegration.jsx
> Don't fail when image does not have any environment set up

- src/ImageRunModal.jsx
- test/check-application
An equal sign can be part of an env variable.
Closes #1090
> Allow equals sign to be entered as env variable

- .github/workflows/npm-update-pf.yml
- .github/workflows/npm-update.yml
- .github/workflows/reposchutz.yml
- .github/workflows/weblate-sync-po.yml
- .github/workflows/weblate-sync-pot.yml
See https://github.com/cockpit-project/cockpit/pull/17811 for more details and test results.
> Update Github workflow actions

- Makefile
- test/run
> test: Collect code coverage

- packaging/debian/control
- packaging/debian/upstream/metadata
> packaging: Sync Debian packaging with downstream

- .eslintrc.json
- src/DynamicListForm.jsx
- src/ImageSearchModal.jsx
This is more readable and automatically applied using `eslint --fix`.
> Enable object property newline rule

- package.json
- src/app.jsx
- src/index.js
https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis
> Upgrade to react 18 and enable the new concurrent renderer

- src/ContainerCheckpointModal.jsx
- src/ContainerCommitModal.jsx
- src/Containers.jsx
- src/PodActions.jsx
- src/PruneUnusedImagesModal.jsx
In the long run we want to get rid of class components.
> Make some components functional components

- src/ImageDeleteModal.jsx
This now also disables the "select all" button if all checkboxes are checked.
> Refactor ImageDeleteModal to a functional component

- src/ImageRunModal.jsx
- src/ImageSearchModal.jsx
`result.reason` is an object and nothing was rendered.
> search: Really show some error messages

- .github/workflows/release.yml
Similar to https://github.com/cockpit-project/bots/pull/4224
> workflows: Pacify git's permission check in release workflow

- Makefile
Build the Python bridge from the cockpit project and install it into the VM so we can run tests against it.
> build: add support for /pybridge scenario

- .github/codeql-config.yml
- .github/workflows/codeql.yml
- src/ContainerRenameModal.jsx
- src/ContainerTerminal.jsx
- src/Containers.jsx
- src/Images.jsx
- src/app.jsx
There are still two issues left, but those require more work to be fixed so let's do that in a follow up. For now this provides some nice code issues so it's worth to already have it.
> Add Github code scanning workflow using codeql

- Makefile
- webpack.config.js
The API of the plugins changed slightly to also support esbuild.
> Update cockpit repo to hybrid webpack/esbuild plugins

- test/check-application
This should fix one of the common flakes in the recent PR's.
> Fix dd flake and improve 

- build.js
esbuild's builtin watch mode has several limitations and issues:
- It uses polling instead of inotify [1], and thus is very CPU intense and laggy
- It does not watch the artifacts handled by the `copy` plugin, i.e. manifest.json and *.html files.
- The initial "build finished" log message from context.watch() comes way too early, before it even started to assemble the dist/ directory. This is very confusing. (Logs for subsequent builds were correct).
This commit implements our own watch mode using node's `fs.watch()` API [2], which fixes all of the above. It does not watch recursively (that option is not supported on Linux), but we don't really need to for cockpit-podman:  src/ does not have subdirectories. For cockpit we'll have to implement watching every subdirectory, but let's keep it …
> build.js: Implement our own watch mode

- Makefile
- build.js
- package.json
Sync up from machines basically :)
> Invoke ./build.js directly

- Makefile
- package.json
- src/ContainerCommitModal.jsx
- src/ContainerHeader.jsx
- src/ContainerRenameModal.jsx
- src/Containers.jsx
- src/Containers.scss
- src/DynamicListForm.scss
- src/ImageHistory.jsx
- src/ImageRunModal.jsx
- src/ImageRunModal.scss
- src/ImageSearchModal.css
- src/ImageSearchModal.jsx
- src/Images.css
- src/Images.jsx
- src/PodCreateModal.jsx
- src/PruneUnusedImagesModal.jsx
- src/PublishPort.jsx
- src/Volume.jsx
- src/app.jsx
- src/podman.scss
- test/check-application
Update to the same PF5 versions as Cockpit. Apply the "-v5" prefixing and import adjustments.
Make use of the new pywrap feature from our test.
See starter-kit commit 2215aa3bf801224.
---
Copy of PR #1299, as that has a broken GitHub API.
> Makefile: Update Cockpit lib to 756b59469637dd2dee00d086b883cffd16dc5efc

- src/ContainerRenameModal.jsx
- src/Containers.jsx
- src/app.jsx
- src/util.js
Another set of fixes broken out of #1324. With that, I got an almost green (everything except [this stupid thing](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1324-20230705-132859-fdd9a1ae-ubuntu-2204/log.html#38)) run.
It' still not where I want it to be, but a big improvement already. But this set of patches is ready now.
> Clean up pod and container removal handling, some code cleanup

- src/app.jsx
- test/check-application
[flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1324-20230706-062110-7b0e3e95-fedora-38-pybridge/log.html#1)
> test: Fix race condition in testBasicSystem pixel test, fix coverage error

- src/ContainerRenameModal.jsx
- src/ImageSearchModal.jsx
trying to solve this good first issue
https://github.com/cockpit-project/cockpit/issues/19061
> onKeyPress is replaced with onKeyDown

- src/Containers.jsx
- src/app.jsx
Rummaging around in podman's state files is inelegant, brittle, and expensive.
> Query checkpoint presence via API

- src/app.jsx
Accidentally introduced in commit 8d8f7d0d8.
> Drop leftover debugging console log

- src/Containers.scss
- src/podman.scss
> fix: Screen width for podman containers

- src/ImageRunModal.jsx
- src/PublishPort.jsx
- src/Volume.jsx
> Replace DynamicListForm's MinusIcon with TrashIcon

- src/ImageRunModal.jsx
- test/check-application
Instead of oops'ing filter out invalid regexp characters.
Closes: #1300
> Filter out unwanted RegExp characters when searching

- Makefile
> Fix updates-testing scenario for F39

- src/ImageDeleteModal.jsx
- src/podman.scss
- test/check-application
> Improve deletion confirmation modal

- test/check-application
Thanks to @subhoghoshX for spotting!
> test: Fix image deletion check

- src/ImageDeleteModal.jsx
- test/check-application
> Allow deleting intermediate images

- Makefile
- src/ImageRunModal.jsx
- src/PodCreateModal.jsx
- test/check-application
Adjust code and tests for the `undefined` "holes" that the data model now gets on deletion.
---
I couldn't reproduce the state confusion from https://issues.redhat.com/browse/RHEL-19598 at least with the port mapping. This only happened in machines with the "validated" SSH  keys, where the whole element was replaced. React magic.. But interactive testing with the updated component still seems to work.
> Update to changed DynamicListForm import from latest cockpit

- src/ImageRunModal.jsx
- src/PodCreateModal.jsx
This aligns with the comment and with how onChange works and is purely an aesthetic change.
> Use key, value style arguments for onValidationChange methods

- Makefile
Commit 9279fd46f1c1a73 didn't apply the hack to the "updates-testing" and "podman-next" scenarios, as these *overwrite* `VM_CUSTOMIZE_FLAGS` to get rid of the `--offline`.
Reorganize VM_CUSTOMIZE_FLAGS a bit to deal with `--no-network` in a cleaner way.
Fixes #1611
-----
I additionally triggered the scenarios here.
> test: Apply pasta hack to scenarios as well

- src/app.jsx
For once we ever convert this to a real Promise API
> Prefer using the Promise API

- test/check-application
Forgotten in commit ff9c7f3419a5
See [latest run](https://artifacts.dev.testing-farm.io/aef1ad09-f8ff-4807-8d7a-6a73340c1d95) in https://github.com/containers/podman/pull/22322
> test: Adjust testRunImageUser() for RestartPolicy API change too

- src/Containers.jsx
- src/Images.jsx
- src/util.js
- test/check-application
See discussion here: https://github.com/cockpit-project/cockpit/pull/20322/files#r1567471946
> cockpit.format_bytes() cleanups

- test/check-application
Played around in this PR https://github.com/cockpit-project/cockpit-podman/pull/1771
> Settle containers lifecycle

- .github/dependabot.yml
- package.json
- src/ContainerLogs.jsx
- src/ContainerTerminal.css
- src/ContainerTerminal.jsx
These are the new names, and they have more recent releases.
> build: Switch to @xterm/xterm and @xterm/addon-canvas

- src/ContainerHeader.jsx
- test/check-application
Superseedes https://github.com/cockpit-project/cockpit-podman/pull/1292
> Allow search filter to be cleared

- packit.yaml
It started working yesterday evening.
> packit: Re-enable Fedora 42

- test/check-application
This should not conflict with your open PR and it is not completely typed yet but I ran out of steam and $hours :)
> test: gradually type more of our tests

- test/check-application
Previously we never had a pixel test for a pod.
> test: take a pixel test of a pod

- test/check-application
Everything is now typed except `self.execute`.
> test: further complete typing of check-application

- src/ContainerLogs.jsx
- src/ContainerTerminal.jsx
- src/Containers.jsx
- src/Env.jsx
- src/ImageRunModal.jsx
- src/PublishPort.jsx
- src/Volume.jsx
Modern linters complain about this while eslint finds it acceptable.
> Prefix all unused variables with `_`

- src/ImageRunModal.jsx
- src/app.jsx
This is the honest version of #2065.
> Various fixes (real)

- src/ContainerDetails.jsx
- test/check-application
Add pixel coverage for:
- prune image modal
- create pod modal
- rename modal
- container details tab
- container integration tab
> test: extend pixel tests

- src/ContainerIntegration.jsx
- src/Containers.scss
- src/Images.css
- src/podman.scss
Went through our CSS to figure out if there are overrides, to remove, document etc.
> General CSS related cleanups and a small bugfix

- pyproject.toml
- test/check-application
This types the last untyped function `execute` which is a bit of a hassle as it has a first boolean argument which should be the last due to our boolean trap rules.
---
A bit of a yak shave but it should work (tm)
> test: fully type check-application

- test/check-application
> test: The ubuntu-stable image now has "criu"

- test/check-application
> test: Replace complicated "has_criu" condition with a image list

- test/check-application
> Various test fixes

- packit.yaml
- test/browser/run-test.sh
This is harmless, but still looks weird.
> packit: Fix test job indentation
