cockpit-project/cockpit-podman

- .eslintrc.json
- lib/cockpit-components-listing.jsx
- lib/cockpit-components-select.jsx
- lib/listing.less
- lib/page.css
- lib/variables.less
- package.json
- src/ContainerDeleteModal.jsx
- src/ContainerDetails.jsx
- src/ContainerHeader.jsx
- src/ContainerRemoveErrorModal.jsx
- src/Containers.jsx
- src/ContainersRunImageModal.jsx
- src/DropDown.jsx
- src/ImageDeleteModal.jsx
- src/ImageDetails.jsx
- src/ImageRemoveErrorModal.jsx
- src/ImageSecurity.jsx
- src/Images.jsx
- src/app.jsx
- src/app.scss
- src/atomic.jsx
- src/index.es6
- src/podman.scss
- src/util.js
- test/check-application
- webpack.config.js
Signed-off-by: Qi Wang <qiwan@redhat.com>
> Implement listing images/containers using React JSX

- Makefile
When the topmost commit isn't tagged, rpmbuild otherwise fails with
error: line 2: Illegal char '-' (0x2d) in: Version: 176-1-g9101a30a
Replace the dashes from `git describe` with periods, to get a valid RPM
upstream version number.
> Fix `make rpm` for unreleased code

- lib/cockpit-components-listing.jsx
- lib/cockpit-components-select.jsx
- Use `import` instead of `require`
- Drop unnecessary keys (they are only necessary for lists)
- Fix Listing title default property
- Support disabled elements in Select
- Allow any data type in Select
> lib: Update Cockpit Listing and Select components

- src/util.js
If the error returned by varlink did not have a `.parameters` field, the
page oopsed with
RuntimeError: TypeError: Cannot read property 'reason' of undefined
This also gets picked up by the test cases often and makes them fail.
> Fix crashes on error reporting

- Makefile
Remove the entire previous overlay instead of just removing the built
package. This ensures that there are no leftovers from previous
interactive debugging sessions.
This has already shown to lead to confusion in practice in
cockpit-podman.
Cherry-picked from starter-kit commit 6e05f5b4837a4
> test: Properly clean up test VM on image preparation

- Makefile
As the current Fedora release.
> Run tests on Fedora 29 by default

- src/ImageDetails.jsx
Images now have their entrypoint, command, and port configuration in the
`Config` instead of the `ContainerConfig` sub-dictionary.
---
This gets spotted by the [current test failure](https://fedorapeople.org/groups/cockpit/logs/pull-11019-20190121-104747-2a99e462-cockpit-project-cockpit-podman-cockpit-fedora-29/log).
> Adjust image configuration JSON structure

- src/ContainerRemoveErrorModal.jsx
Fixes this React warning:
```
error: Warning: Received `false` for non-boolean attribute `fade`. If this is expected, cast the value to a string.
in div (created by CustomModalDialog)
in CustomModalDialog (created by Modal)
in Transition (created by Fade)
in Fade (created by DialogTransition)
in DialogTransition (created by Modal)
in RefHolder (created by Modal)
in div (created by Modal)
in Portal (created by Modal)
in Modal (created by Modal)
in Modal (created by ContainerRemoveErrorModal)
```
> Drop non-existing fade property from Modal

- src/ContainerDetails.jsx
- src/ImageDetails.jsx
- src/Images.jsx
- src/util.js
Podman uses the format of golang's `time.String()` to output times in
the varlink API. That doesn't output time in a standard format that
moment.js recognizes.
This makes all times show up as readable times again and gets rid of a
warning by moment.js on the console.
Fix this by explicitly passing a format string. Also filed upstream:
https://github.com/containers/libpod/issues/2260
Depends on:
> Pass podman's time format into moment() calls

- src/app.jsx
- src/varlink.js
- test/check-application
See individual commits. Now, if the socket isn't running, the page looks like this
Which is much more useful than the previous confusing state where the lists were shown, but empty.
This isn't perfect yet, e. g. the page does not *watch* for the socket to go up and down (we might copy cockpit's services.js for that?). But it should hopefully cover the most common problem scenario.
> Add empty state pattern for non-running service, and some bug fixes

- package.json
This reverts commit 5d3aebcf962264dd08e0beef80fcaf73dab14640.
terser 3.16.1 got released which fixes the regression.
> Revert "package.json: Pin down terser 3.14.1"

- cockpit-podman.spec.in
- org.cockpit-project.podman.metainfo.xml
- Add missing XML header
- Validate format as per documentation:
https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/#_app_data_validate_usage
> Fix and validate AppStream metainfo

- src/app.jsx
- src/varlink.js
Return a promise from `varlink.connect()` that resolves when the channel
signals that it is ready. This is not technically needed, because
cockpit allows sending messages to channels before they're ready. It is
a bit cleaner though, because clients can be sure that connections have
been established before starting to send messages.
This was already expected in `varlink.call()`, which is also the only
consumer of this call.
> varlink: Return a promise from varlink.connect()

- cockpit-podman.spec.in
Use the same 17-column row for the property keys and aligned values as
in cockpit and composer. This will provide a consistent result from
cockpituous' release-srpm when it adds/modifies Version: and Release:.
> spec: Align property values

- src/ContainerCommitModal.jsx
- src/Containers.jsx
- src/Notification.jsx
Container.jsx file is home to much code that should be split into different files. This makes this file a total mess.
By moving all the code related to ContainerCommit to the ContainerCommitModal we can get rid of all these useless handlers that we need to pass around the react components otherwise.
Also error messages previously were printed like JSON.stringify(ex) which is definitely not a user friendly way to tell 'you container commit failed'. So I changed a bit the presentation of error messages as well.
> Move commit modal handler code into the CommitModalComponent and enhance error messages

- Makefile
- test/check-application
These are obsolete since
https://github.com/cockpit-project/cockpit/commit/b1722f5b5d0
Bump cockpit test API accordingly.
> test: Remove redundant wait_present() calls

- package.json
We now let the Cockpit npm-update bot update these in a controlled
manner.
> package.json: Pin dependencies to exact versions

- src/Containers.jsx
Clicking a container row was wired up to go to the container's details
page, which we don't have yet.
Remove it until we do.
Fixes #89
> Containers: Expand on click

- src/ContainerCommitModal.jsx
- src/ContainerDetails.jsx
- src/Containers.jsx
- src/ImageDetails.jsx
- src/ImageRunModal.jsx
- src/util.js
- test/check-application
Using command like `sh -c "while date; do sleep 2; done"` to create new
container would fail with executable not found as it took the whole line as an executable.
This commit makes it possible to use arguments in the command.
Also show as default command image cmd.
> Cmd with arguments

- cockpit-podman.spec.in
- src/ImageRunModal.jsx
- src/Images.jsx
- src/app.jsx
Since version 1.3.0 (with epoch 2) there has been some changes in API,
cockpit-podman has been affected with the create type.
There were four changes, which needed to be addressed:
1) env is not map but array of 'key=value'
2) image is passed in array `args`
3) command is passed in array `args`
4) `volumes` option has been renamed to `volume`
These changes were introduced to better match commandline options from
podman itself.
Note about tests:
f30 - this image has this new version and naughty, since it was failing. Expected result is that all tests pass without the naughty being used.
> Update to the new create type

- src/podman.scss
This little thing was too annoying, needed to fix it :)
Current master:
With this patch:
> Align filtering and searching fields

- cockpit-podman.spec.in
There, the podman package does not have an epoch.
> spec: Fix podman dependency on RHEL 8

- cockpituous-release
Use release-srpm's `-V` option [1] so that the generated srpm will get a
proper changelog and Release "1" instead of "2".
[1] https://github.com/cockpit-project/cockpituous/commit/abb2bdb5
> cockpituous: Fix srpm Release:

- lib/form-layout.less
However, revert the change of reducing the number of supported splits
from 3 to 2, as the port and volumes lines do use 3 columns.
> Sync form-layout.less with Cockpit master

- package.json
- src/ContainerDetails.jsx
- src/ContainerTerminal.css
- src/ContainerTerminal.jsx
- src/Containers.jsx
- test/check-application
When container is not running not terminal is shown.
When container is started while container details are opened, terminal
shows up. When container stopped while details are opened, "disconnected"
message is shown and terminal is kept open (however you cannot write
into it).
When container is interactive (such as executed `sh`) a prompt is shown.
This is done by sending SIGWINCH signal (podman does the same on
`attach`).
TODO:
Used to look like this:
Stopping container shows disconnected:
There is one small issue I am aware of and that being that when terminal is not interactive and is just logging (like `sh -c "while echo hello; do :; done"`) then SIGWINCH signal leaves `^L` on first line. But for now I take this as for follow up. Ideas welcomed :)
Note about tests:
This won't work …
> Introduce terminal

- test/check-application
> test: Accept both "stopped" and "exited" states after force-stopping container

- test/check-application
https://github.com/cockpit-project/cockpit/pull/12265 changed the design
a lot, so that `#service-unit` does not exist any more.
The tests need to get along with the old and new design, so just relax
the check.
> test: Adjust to changed Cockpit Services page

- org.cockpit-project.podman.metainfo.xml
Cockpit renamed its ID to "org.cockpit_project.cockpit" to conform to
the AppStream spec [1]. Follow suit and also fix our own ID to not
contain hyphens.
[1] https://github.com/cockpit-project/cockpit/commit/4a9ffe669c
> Fix AppStream ID

- src/ContainerRemoveErrorModal.jsx
- test/check-application
Can be tested with
```
make vm
bots/vm-run fedora-30
test/check-application -tv --machine 127.0.0.2:2201  --browser 127.0.0.2:9091
```
> test: Allow tests to run on existing testbed

- .eslintrc.json
Eslint shimmies up directories looking for more eslintrcs. As
make-checkout now clones projects in a subdirectory, this can result in
some strange interactions.
https://eslint.org/docs/user-guide/configuring
> eslintrc: Set "root" to true

- Makefile
This is not needed any more since
https://github.com/cockpit-project/bots/pull/134
This reverts commit a6e1390c5ed946d469b763cf2c4b88fb4b1e8326.
> Revert "Use dnf when preparing VM"

- Makefile
- src/ContainerCommitModal.jsx
- src/ContainerTerminal.jsx
- src/Containers.jsx
- src/ImageRunModal.jsx
- src/ImageSearchModal.css
- src/ImageSearchModal.jsx
- src/ImageUsedBy.jsx
- src/Images.jsx
- src/app.jsx
- src/podman.scss
- src/util.js
- src/varlink.js
- test/check-application
- test/vm.install
This implements showing of user owned containers. Can be tried with [this](https://mmarusak.fedorapeople.org/podman-1.4.5-1564481722.gita4928fff.fc30.x86_64.rpm) podman build.
Fixes #84
Fixes #83
Blocked on:
TODOs:
Follow-ups:
> Show user owned containers and images

- src/ImageRunModal.jsx
- test/check-application
Fixes #167
I am not sure what the default value should be. In docker we had 1024, but when I don't specify it, podman starts with 0. So should I use 0 as well?
> Enable to limit cpu

- test/check-application
We restart container and then check its pid has changed. We should wait
for this change, as the restarting may take longer time.
Fixes #269
> test: Wait for container to restart before checking its pid

- src/app.jsx
We showed the page when one service was detected, which meant we always
shown alert mentioning the other service is available as well, even when
the service was running. We closed this warning after a few seconds.
> Wait until both services are detected

- src/Containers.jsx
- src/Images.jsx
- test/check-application
Both images and containers need to be grouped by the user. And each
group needs to be ordered by names.
Before this commit, if you would create new container or download a new
image, it would be appended at the bottom of the list. Also there was no
given order of which group (if system or user) would be first.
I decided to show user images above system ones and the same with
containers.
Fixes #222
> Keep order of containers and images

- src/ContainerCommitModal.jsx
- src/util.js
- test/check-application
Issue https://github.com/containers/libpod/issues/3897 has been fixed a
few months ago, it reached Fedora 30 and 31 as well as RHEL 8.2.
^^ I haven't tested it, this is what I hope is true. Maybe it needs to be skipped on rhel-8-1, and maybe not (if the broken version never made it into 8.1).  Let's see what tests say.
> Fixes and testing of commit 

- src/ImageRunModal.jsx
- test/check-application
Minimum value is 2.
Default value is 1024. We still test that if we don't set it up, it is
0, but for that see https://github.com/containers/libpod/issues/4822
Fixes #287
> Fix default and minimum value for CPU Shares

- test/check-application
`sleep` without argument is not valid command, but we don't run those
images anyway. And once it is fixed in podman, we want to change this
back.
See https://github.com/containers/libpod/issues/4847
> test: Work around podman not being able to change CMD in commit

- Makefile
I miss the TEST_SHOW_BROWSER feature in podman.
> Makefile: Bump test API version

- lib/cockpit-components-listing.jsx
- lib/listing.less
- lib/page.css
The obvious difference is that items in listing are taller (have more padding):
> lib: Sync up with current Cockpit master

- src/ContainerLogs.jsx
Seems that `reset()` displays the cursor again.
> logs: When resetting the view, hide the cursor again

- cockpituous-release
It branched off on Feb 11:
https://fedorapeople.org/groups/schedule/f-32/f-32-key-tasks.html
> cockpituous: Release to Fedora 32

- lib/page.css
@patternfly/react-styles 3.7 stopped shipping a copy of
patternfly-variables.css. Import it from @patternfly/patternfly instead.
package.json explicitly depends on the latter, but not on the former, so
we don't have control over react-styles.
The file is identical to the one from @patternfly/react-styles 3.6.4
(the version which we used until yesterday).
Cherry-picked from cockpit-project/cockpit from 4ace78c
> lib: Import patternfly-variables.css from main module

- test/vm.install
fedora-* ≥ 31 images start to have a cockpit/base and its parent fedora
container image in <https://github.com/cockpit-project/bots/pull/562>.
Our tests don't expect that. Keep the test strict (as we want to check
precise ordering) and remove the unexpected images instead.
> test: Clean up unexpected system podman images

- test/check-application
With https://github.com/containers/libpod/commit/c1e269 the default CPU
share now gets displayed as 1024 instead of 0.
> test: Fix testRunImageSystem for podman 1.8

- src/Images.jsx
- test/check-application
- test/vm.install
Revert "test: Clean up unexpected system podman images" (commit
ac71eccda).  This was not a good solution, as the test still breaks for
downstream gating -- that image has at least one expected cockpit/tasks
image.
Instead, make sure that images are sorted first by user/system and then
alphabetically. Don't bother with asserting the insertion order of the
committed container images, just make sure that they are present.
This requires closing the expander again, as otherwise checkImage()
treats the expander context as part of the string.
> test: Tolerate extra podman images

- Makefile
We have never observed https://bugzilla.redhat.com/show_bug.cgi?id=1762663
in Fedora 32, and it does not seem to happen with current Fedora 31 any
more either.
> Makefile: Drop hack for fixed kernel bug

- test/vm.install
Just like with the other two images, explicitly pull busybox from the
docker.io registry. This avoids unnecessary lookups to, and possibly
getting a different image from e. g. the Fedora registry. Latest skopeo
also seems to either disallow (deliberately) or break (inadvertently)
lookups without a registry.
> test: Specify registry for busybox

- test/check-application
Nightlies still have old podman 1.6.x.
> test: Fix tests for rhel-8-3

- test/vm.install
Without this, `$XDG_RUNTIME_DIR` defaults to /tmp/run-1000/libpod/tmp,
which creates a mismatch in the created configuration.
See https://github.com/containers/libpod/issues/5950
> test: Pull user podman images with proper XDG_RUNTIME_DIR session

- test/check-application
Should fix https://github.com/cockpit-project/bots/pull/826
It is gonna be a bit tricky to get tests green, so I will do:
1. trigger all tests + `rhel-8-2@bots#826`
2. If passed merge the bots PR
3. re-test this
> test: RHEL-8.2 has sufficent podman version now

- Vagrantfile
Fedora 28 is not available anymore as box this bumps it to the latest version 32.
It also adds `podman` as package to install for convenience.
> Update vagrant box

- test/check-application
Both old and new services page has `#service-details`.
As found in #381 and #382
> test: Adjust to new services page

- Makefile
- test/check-application
- test/vm.install
The flake was presented as
```
wait_js_cond(ph_text_is(".container-logs .xterm-accessibility-tree > div:nth-child(6)","6")): .container-logs .xterm-accessibility-tree > div:nth-child(6) not found
```
for example [here](https://logs.cockpit-project.org/logs/pull-385-20200523-055607-c3346b67-fedora-32/log.html)
> Adjust to new cockpit + flake fix

- test/check-application
RHEL 8.3 nightly has podman 1.9 now.
> test: Drop rhel-8-3 special case for podman < 1.7

- test/check-application
Invert the test, so that we have a shrinking instead of growing list.
> test: Apply podman 2.0 inspect format to Fedora 31 as well

- lib/page.css
- lib/patternfly/patternfly-4-cockpit.scss
- lib/patternfly/patternfly-overrides.scss
- src/ImageSearchModal.css
- src/app.jsx
- src/podman.scss
I ran codespell across cockpit-podman and it found these errors. Some of these are probably fixed in Cockpit itself, so a sync up would fix a bunch anyway.
(There were a few with "master" as well, but those are all URLs to git repos.)
> Fix spelling

- org.cockpit-project.podman.metainfo.xml
`<launchable>` must coincide with the actual URL path defined by the
manifest.
Also remove the redundant "Cockpit" from `<name>`, as all of these
extensions are about Cockpit. This makes the "Applications" page more
consistent.
Remove the period from `<summary>`, as the spec [1] suggests.
[1] https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent
https://bugzilla.redhat.com/show_bug.cgi?id=1854673
> metainfo: Fix launchable and update description

- org.cockpit-project.podman.metainfo.xml
`<launchable>` must coincide with the actual URL path defined by the
manifest.
Also remove the redundant "Cockpit" from `<name>`, as all of these
extensions are about Cockpit. This makes the "Applications" page more
consistent.
Remove the period from `<summary>`, as the spec [1] suggests.
[1] https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent
https://bugzilla.redhat.com/show_bug.cgi?id=1854673
Cherry-picked from master commit 8dc58334d
> [rhel8] metainfo: Fix launchable and update description

- cockpituous-release
This is a stable branch aimed at RHEL.
> cockpituous: Only release to GitHub and COPR

- src/podman.scss
When reviewing #244, I noticed the details for the containers and images are in a simple definition list. I've added a bit of CSS that uses PF4 variables to arrange the same content in a simple grid, consistent with the look of PF4's forms. (This isn't a form, so it shouldn't use `<label>`s and various form widgets. A `dl` is fine.)
> Arrange container and image details in a grid

- src/podman.scss
This value is set to '2' in `lib/form-layout.scss` but it is getting
broken often on sync. (last such case was 0c8e511)
Lets have custom overwrite rather than being super careful on library sync.
Before:
After:
> Fix alignment in 'Run Image' dialog

- test/check-application
This simple tests was too quick and it left VM in destructed state.
I could not figure out the exact problem, it seems that we cleaned up
podman directories while it was still init-ing them.
Thus moved it into testBasicSystem. However if I logged out too quickly
and there was still some event coming in, it coredumped podman so I just
wait until the last container is exited. This needs report, but rather
tricky to reproduce.
> test: Include testRootUser into testBasicSystem

- Makefile
This brings in the run-tests fix that breaks Fedora dist-git gating
tests: https://github.com/cockpit-project/cockpit/commit/4d3841e321a8
> test: Bump Cockpit test API to 223

- src/Images.jsx
- src/podman.scss
- test/check-application
If there is at least one such image, show 'Show intermediate images'
button, but don't show these images in the list. When this button is
clicked, these images are shown and button label changes to 'Hide
intermediate images'.
Fixes #214
> Better manage intermediate images

- lib/cockpit-components-listing-panel.jsx
Fixes keyboard navigation of NavItem on expandable table rows.
Note: this is not `yet` in cockpit/master but in https://github.com/cockpit-project/cockpit/pull/14383
> lib: sync ListingPanel component with cockpit/master

- src/ContainerCheckpointModal.jsx
- src/ContainerRestoreModal.jsx
- src/Containers.jsx
- src/app.jsx
- test/check-application
- test/vm.install
Adds support of local container checkpoint and restore (without export and import) using the CRIU integration with Podman.
Tests for this feature are not included, because Podman checkpoint and restore doesn't work on Fedora 31 yet.
> Support local checkpoint and restore

- src/ContainerCheckpointModal.jsx
- src/ContainerDeleteModal.jsx
- src/ContainerRemoveErrorModal.jsx
In `ContainerRemoveErrorModal` was typo and no container name was shown
and the two others shown container sha, which is not super user friendly
and not consistent with rest of c-podman.
> Use container name in modal titles

- src/Images.jsx
- src/podman.scss
Aligning the style of the button to the rest of Cockpit.
(I'm unsure why it was ever a link. I know cockpit-docker did the same, so I know cockpit-podman inherited the style.)
Screenshot:
> Swap new image button from link-style to secondary

- test/check-application
Stop user's podman.service at the end of the test, before restoring the
directories.
> test: Fix cleanup of user podman

- src/ContainerTerminal.jsx
- test/check-application
These headers were ignored before 2.0.4, but are required since.
> Fix attaching to containers with new version

- test/check-application
- test/vm.install
Our Fedora/RHEL CI images have the cockpit/base and the underlying
fedora container image, but the Debian image does not. Avoid the
ambiguity by cleaning up all existing images in vm.install.
> test: Drop existing podman images

- test/vm.install
This avoids running into the API breakage of 2.0.3:
https://github.com/containers/podman/issues/7078
> test: Install podman 2.0.4 from updates-testing

- test/vm.install
2.0.9 breaks `podman exec`:
https://github.com/containers/podman/issues/5339
> test: Update to conmon 2.0.18 in Debian unstable

- cockpit-podman.spec.in
- packaging/debian/control
This makes sure that we don't use this with the broken 2.0.3 version.
> Bump podman dependency to 2.0.4

- src/ContainerHeader.jsx
- src/Containers.jsx
- src/Containers.scss
- src/Images.jsx
- src/app.jsx
- src/client.js
- src/podman.scss
- test/check-application
> Add support for pods (and some Ui refactoring)

- packaging/debian/copyright
Fix the Upstream-Name.
Adjust the comment to better describe how cockpit-podman release
tarballs look like.
> packaging/debian: Copyright clarifications

- Makefile
Upgrade podman/container related packages and the kernel to rawhide, so
that we can test it on demand.
Note: The `--releasever` option is necessary to force dnf to download
and install the correct GPG keys. This assumes that this runs on the
most recent stable Fedora release (i.e. fedora-32 at the time of
writing) that precedes rawhide.
> test: Add Fedora rawhide scenario

- test/check-application
In this test we create and delete many containers named 'test-sh' from
'alpine' image. There exists race, where in the UI we still see the
previous 'test-sh' container, that we think we already deleted and
expect to see a new 'test-sh' container in the UI we just created. When
we are fast enough, we have time to toggle open the container details,
but then it gets deleted, a new container is rendered but it does not
have details expanded.
Thus let's name every container uniquely and when we target specific
container line, let's do it by its name and not by its image (which
makes so much more sense anyway).
Should fix flake like [this](https://logs.cockpit-project.org/logs/pull-499-20200806-160515-6e8157f5-fedora-32-rawhide/log.html)
> test: Wait for proper containers in the UI

- src/ContainerDetails.jsx
- src/ImageDetails.jsx
- src/Images.jsx
- src/util.js
- test/check-application
This was introduced somewhere between 2.0.4 and 2.1.0.
Our `fedora-32/rawhide` already sees that, but not our other images.
I have to add there some condition so it works also with 2.0.4 but I want to spin tests once now to see it really is needed for rawhide.
> Image create time moves to timestamp

- cockpituous-release
Bodhi activation point is the [next Tuesday](https://fedorapeople.org/groups/schedule/f-33/f-33-key-tasks.html). We won't have another release in the meantime so lets not forget about it. I'll start preparing F33 image now so we can also test it.
> cockpituous: Release to Fedora 33

- cockpituous-release
Fedora 33 is branched now, let's not support too many releases in
parallel.
> cockpituous: Stop releasing to Fedora 31

- po/cs.po
- po/de.po
- po/es.po
- po/fr.po
- po/pl.po
- po/pt_BR.po
- po/pt_PT.po
- po/sk.po
- po/tr.po
- po/uk.po
- po/zh_CN.po
Done with:
```
FILES=po/*.po
for f in $FILES; do msguniq -o $f $f; done
```
I did this in weblate repo but completely forgot to do it also in this
repo. See https://github.com/cockpit-project/cockpit-podman-weblate/commit/4147632b
> po: Fix duplicate strings

- Makefile
- test/check-application
On the login page the `Reuse password` checkbox was dropped and that
makes all the tests to fail.
See https://github.com/cockpit-project/cockpit/commit/ef97e7e9a28a
> test: Bump test/common to 228

- test/check-application
Otherwise, "systemctl --user disable podman.socket" has no effect on
"systemctl --user is-enabled".
> test: Disable podman.socket globally for the tests

- test/vm.install
We are dropping docker from the debian image.
See https://github.com/cockpit-project/bots/pull/1262
> test: Don't require docker.service

- test/vm.install
The podman package's dependencies now prefer crun, so the previous hack
for https://bugs.debian.org/961016 is obsolete (and that bug is closed).
However, podman *really* defaults to runc, so explicitly install it
for now until the default configuration or dependencies get fixed:
https://bugs.debian.org/971253
This was previously hidden because the debian-testing image contained
docker.io, which pulls in runc. But
https://github.com/cockpit-project/bots/pull/1262 removes docker.io, and
runc with it.
> test: Explicitly install runc on Debian testing

- po/html2po
- po/manifest2po
- po/po2json
- test/run
The current version failed with
Option "--directory" requires 1 arguments, but 0 were provided
In the current stdio npm module version, getopt() now requires a
`default:` attribute, otherwise it considers the options as required.
Also sync PO helpers with current cockpit.
Cherry-picked from cockpit-project/starter-kit commit cbedf06
Checked and .pot file is built correctly. When we land this we need to retry #550
> Fix building PO template

- src/app.jsx
- test/check-application
In https://github.com/containers/podman/pull/7202 a new event was
introduced. Listen on it as well.
This is not going to work out just now, but I am opening it now, so we won't forget. Once new podman (I guess 2.0.5 should get it) is out and in our VMs, we can nicely verify it with retrying tests in this PR.
> Listen on event for image build

- .github/workflows/npm-update.yml
- .tasks
- README.md
This avoids a lot of moving parts in our infrastructure (webhook,
npm-trigger roundtrip, tasks container) and does not need *any* secret
other than the automatically provided GitHub token.
Adopted from starter-kit: https://github.com/cockpit-project/starter-kit/pull/384
> Run npm-update in a GitHub workflow

- .github/workflows/po-refresh.yml
The automatic default `GITHUB_TOKEN` only has access to the originating
repo (cockpit-project/cockpit-podman), not to the weblate repository.
Use a token for the github.com/cockpituous bot user for that.
> workflows: Use cockpituous token to push to weblate repository

- package.json
Locally I had to edit package.json to be actually able to build this project, so want to check with CI if there is the same problem or not.
>  package.json: Add 'file-selector' dependency

- test/vm.install
This makes the script reusable in environments like GitHub, GitLab,
Travis, or Debian/Ubuntu autopkgtest.
- Build debs directly on the machine if pbuilder is not available.
- Create admin user and set up SSH to root for test.
- Make test/vm.install executable, so that it can be called easily
directly.
- Support passing additional options to `apt-get install`.
> test: Support generic Debian environments

- .travis.yml
Travis now offers /dev/kvm, and its machines are powerful enough to run
our browser integration tests, at least for small projects.
Building an RPM on the Ubuntu host environment is a bit tricky, as there
are no installed RPMs. Thus ignore the BuildRequires, and install
appstream-util explicitly. In the future, the rpm build should happen
inside the VM (like Cockpit does).
Add initial scenario for current Fedora.
Switch to the "minimal" environment to make the test easier to reproduce
locally and more explicit.
> Run integration tests in Travis

- Makefile
This file is not shipped in tar file.
Oh wow, someone took picture of me while I was writing this patch:
seriously, WDYT @martinpitt, does it make sense? The point it that if someone tries to build it from tar file it reports:
```
/usr/bin/make install DESTDIR=/home/jnovy/rpmbuild/BUILDROOT/cockpit-podman-25-2.el8.x86_64 'INSTALL=/usr/bin/install -p'
error: Unable to open cockpit-podman.spec.in: No such file or directory
```
> Makefile: Don't parse rpm name from `spec.in`

- src/ImageSearchModal.jsx
We close current search connection if the term has been updated in the
meantime. That results in getting empty reply that cannot be parsed as
valid JSON.
Fixes #595
> Don't show error message when we close connection during image search

- src/ContainerCheckpointModal.jsx
- src/ContainerCommitModal.jsx
- src/ContainerRemoveErrorModal.jsx
- src/ContainerRestoreModal.jsx
Fixes #504
Note: ideally we should be able to cancel the operations but podman does
not offer that, so let's just be safe with not allowing the users to
close the dialogs.
> Disable all ways of closing dialogs while an operation is in progress

- test/vm.install
This avoids pulling the images twice, redudes pull limit stress, and
ensures that the images are identical.
----
I'll also update our Fedora/Debian images to pre-pull these container images and pre-install cockpit and podman; then `make vm` should be completely offline and also much faster.
> test: Copy system podman images to admin user

- src/ImageRunModal.jsx
- test/check-application
Follow what CLI allows:
```
--publish, -p=ip:hostPort:containerPort | ip::containerPort | hostPort:containerPort | containerPort
```
Does not yet supports IP addresses. (so just the last two cases)
Also changing order as it is like that everywhere including in our UI
where we show `IP:hostPort->ContainerPort/protocol`
Fixes #365
> run: Make hostPort optional

- src/ImageRunModal.jsx
- test/check-application
Fixes #412
For release notes:
Enable setting up IP address when exposing container ports
If host IP is set to 0.0.0.0 or not set at all, the port will be bound on all IPs on the host.
> run: Enable setting up IP address for exposed ports

- Makefile
- src/Notification.jsx
- test/check-application
> tests: Make it pass on rhel-8-3 and rhel-8-4

- .github/workflows/npm-update.yml
- .github/workflows/po-refresh.yml
GitHub's base VMs don't automatically refresh package indexes, so it can
happen that one of the package dependencies get out of date and are not
available on the mirrors any more.
Run `apt update` first to ensure that the workflow installs the latest
packages.
> workflows: Fix apt installation

- Makefile
- lib/_global-variables.scss
- lib/cockpit-components-file-autocomplete.jsx
- lib/cockpit-components-table.jsx
- lib/cockpit-components-table.scss
- lib/ct-card.scss
- lib/page.scss
- package.json
- src/podman.scss
- webpack.config.js
Explicitly include the required PF variables definitions into components
instead. This lessens the already gross duplication in the built
index.css (1200 → 950 kB in debug mode). It also makes separate
compilation and reuse easier, and paves the way for using sassc (which
doesn't support global resources).
Also drop the `~` prefix from cockpit-components-table.scss imports.
It's not necessary for sass-loader, and does not work with sassc.
> Drop sass-resources-loader

- cockpit-podman.spec.in
Taken from Troy Dawson's downstream commit:
https://src.fedoraproject.org/rpms/cockpit-podman/c/04f4a72c7033056690
due to removing `make` from the buildroot:
https://fedoraproject.org/wiki/Changes/Remove_make_from_BuildRoot
> spec: Add BuildRequires: make

- src/podman.scss
This was not working in webkit browser. Now it works in webkit, firefox
and chrome.
Fixes #615
Closes #616
Webkit before:
Webkit after:
> Always fill the page with gray background

- .github/workflows/npm-update.yml
- .github/workflows/po-refresh.yml
GitHub's 18.04 additional repositories break NPM. As "ubuntu-latest" is
going to switch to 20.04 soon anyway [1], do the jump now.
[1] https://github.com/actions/virtual-environments/issues/1816
Cherry-picked from starter-kit commit 33a66592.
> workflows: Move npm-update and po-refresh to Ubuntu 20.04

- Makefile
- test/check-application
As seen in https://github.com/cockpit-project/bots/pull/1497
I expect Fedora-32(/rawhide) tests to fail, but the `@bots#` versions to succeed.
> Fedora 32 and 33 now can checkpoint containers on CGroupsV2

- src/client.js
- test/check-application
We have shown error on every pull because we tried to parse the whole
response as one JSON, but in fact it is a group of JSONs. That meant we
failed to notice the fact that we were not showing any useful error when
downloading actually failed. (We always just shown that we could not
parse the response)
Fixes #640
> Fix error and success handling on image pull

- test/check-application
Fixes https://github.com/cockpit-project/bots/pull/1489 where `$XDG_RUNTIME_DIR` is `/run/user/1001`.
> test: Don't assume $XDG_RUNTIME_DIR

- test/check-application
All supported Fedoras use cgroupsv2 now, and this was previously missing
fedora-34 (current rawhide).
> test: Generalize cgroupsv2 distro check

- test/vm.install
This reverts commit 03944ea904ab41282922c2260a5e3ee828e6fc89.
Since https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=971253 has been
fixed, we can safely revert back to the 'crun'
Fixes a failure in https://github.com/cockpit-project/bots/pull/1531
> Revert "test: Explicitly install runc on Debian testing"

- test/check-application
Fixes a failure in debian-testing image refresh:
https://github.com/cockpit-project/bots/pull/1544
> test: Allow debian-testing to cgroupsV2

- src/ContainerLogs.jsx
- src/ContainerTerminal.jsx
- src/Containers.jsx
- src/ImageRunModal.jsx
- src/ImageSearchModal.jsx
- src/ImageUsedBy.jsx
- src/Images.jsx
- src/app.jsx
- webpack.config.js
Just tell webpack to resolve modules in lib/ instead.
This is preparation for moving the library to src/lib for consistency
with starter-kit.
> Stop hardcoding library paths

- Makefile
- packit.yaml
This does not *quite* work yet, as the recent packit fixes https://github.com/packit/sandcastle/pull/92 and https://github.com/packit/sandcastle/pull/94 are not in production yet. But @TomasTomecek 's test in https://github.com/TomasTomecek/cockpit-podman/pull/1 on staging was successful at last. So I'd like to land this already so that their integration tests (which run cockpit-podman now, yay!) have a chance of succeeding.
> Some packit fixes

- package.json
Without that, `npm run watch` is entirely silent after the first build,
and does not give any feedback when a build starts, and even more
importantly, when it's done.
Cherry-picked from starter-kit commit 71a321cc28
> Enable webpack watch progress

- cockpit-podman.spec.in
- packaging/debian/control
- src/app.jsx
- src/index.html
- test/check-application
cockpit-system is not strictly a requirement. In "remote ssh host" mode,
the Podman UI works just fine with just cockpit-{podman,bridge}.
----
It looks a little unfamiliar, but there is not actually anything wrong with this:
> spec: Drop cockpit-system dependency

- cockpituous-release
Fedora "master" branches were renamed to "main".
> cockpituous: Rename Fedora rawhide branch

- cockpituous-release
Turns out "main" is just some kind of alias. Let's use "rawhide"
directly.
> cockpituous-release: Rename Fedora rawhide branch to "rawhide"

- cockpituous-release
Fedora 34 branches from Rawhide today:
https://fedorapeople.org/groups/schedule/f-34/f-34-all-tasks.html
bodhi will get enabled in two weeks, so don't add that yet.
> cockpituous: Add Fedora 34 koji builds

- test/check-application
Upstream podman commit
https://github.com/containers/podman/commit/b53cb57680a6fd7b383636ac2d6cd71003532915
has changed the capitalization.
> Be case-insensitive when checking the error message on checkpoint/restore

- cockpituous-release
- package.json
bodhi activation for Fedora 34 is today [1]. Drop Fedora 32 instead,
which is soon EOL.
[1] https://fedorapeople.org/groups/schedule/f-34/f-34-key-tasks.html
> cockpituous: bodhi for Fedora 34, drop Fedora 32

- test/check-application
It looks like RHEL newer 8.y versions won't get cgroupsv2 either, so
generalize the check.
> test: Generalize cgroupsV2() for all rhel-8-* versions

- .github/workflows/livetest.yml
Previously it was checking out origin/master not the PR's branch.
> livetest: fix cloning of repo

- test/browser/run-test.sh
Our tests don't currently have special cases for fedora. If they ever do
get them again, let's add the rawhide version right away. They will be
gated by packit tests, and we just keep forgetting about this hack.
> fmf: Drop rawhide version override

- test/browser/browser.sh
The initial installation of podman on the Fedora 33 Testing Farm
instances somehow pulls in an old version 0.15.5:
https://github.com/psss/tmt/issues/682
As a quick workaround, ensure that podman and crun are the latest
version, so that criu support is available.
---
This fixes the recent [packit failures on f33](http://artifacts.dev.testing-farm.io/33fd92a3-0d95-4bee-a51b-3faa49fa07a9/).
> fmf: Update crun and podman packages

- src/Containers.jsx
- src/app.jsx
- test/check-application
This functionality was introduced in commit b5f8df880 and broken by
f1e7c9b1518 (and was previously not tested at all). Partially revert the
latter commit and move the "container filter" state back to Application,
so taht the `<Images>` component can use it. Supply a `showAll` property
to that, as it expects it.
Add an integration test which clicks on the "used by" containers and
cover both the running and the stopped case. The former does not really
do anything right now (that's another bug), but check that the latter
switches to "all containers" view and makes the stopped container
visible.
> Fix crash on clicking on "Used by" for stopped containers

- package.json
- packit.yaml
- webpack.config.js
Mostly cherry-picked from recent starter-kit PRs.
> Move to webpack 5

- Makefile
- test/vm.install
It is already present on all our test images, and trying to
install/upgrade it again touches the network. That is often unreliable
and makes tests less reproducible.
For cockpit-podman.rpm itself, upload that and install it with rpm, so
that dnf does not try and update the package metadata. This is the same
approach as with the debs.
-----
Fixes annoying errors like [this one](https://logs.cockpit-project.org/logs/pull-712-20210422-022404-fe2ac86a-rhel-9-0/log.html). The same happened to cockpit-machines today, which I fixed in https://github.com/cockpit-project/cockpit-machines/pull/120 . This is exactly the same fix minus the `--no-network`, as we need networking for the container pulls.
> Stop explicitly installing cockpit-ws

- Makefile
- test/browser/browser.sh
All supported operating systems have this fixed now.
> test: Drop workaround for wrong Type= in podman.services

- Makefile
- test/check-application
- test/vm.install
This fixes "DeprecationWarning: Compilation.assets will be frozen in future" as this now uses the updated cockpit-po-plugin.
I visually tested this build, and it looks ok to me (updated PF CSS and such).
I also added a more robust workaround for https://github.com/cockpit-project/bots/issues/1956 (which will solve this naughty).
> Bump cockpit test API and library to 243

- test/check-application
It seems that this can hit system podman as well. Let's see how this behaves.
> test: Don't check if user or system service failed to start

- Makefile
"current + 1" might not be rawhide once the next version has been
branched, and "current" isn't the most recent release anymore.
> build: Use --releasever=rawhide instead of "current + 1"

- src/Images.jsx
- test/check-application
The images group menu is now a kebab menu to accommodate space for "Prun
unused images" in the future.
> Convert the "Download new image" button to a kebab menu

- src/ImageRunModal.jsx
- src/ImageRunModal.scss
- src/podman.scss
- test/check-application
First step of converting the create container modal to the new re-design, converting the form into two tabs, details and integration. The source/image/tag fields have been redesign fields have been left out for now
Some minor tweaks are applied to set the default value of CPU shares, tweak width of input fields (so they don't take up the full width).
@garrett  we now show as if the default memory limit is 512 MiB, while the default is to take up all available memory.
@garrett you mentioned the "Start after creation" checkbox has no label, how can we add a label without duplicating text?
@KKoukiou is there an issue way to adjust the name label to take up less width so it aligns more with the [design](https://github.com/cockpit-project/cockpit/discussions/16059).
> Redesign create container modal

- .gitignore
Ignore the temporary qcow2 image from vm-run.
> .gitignore: add ./bots/vm-run temporary files

- .gitignore
- Makefile
- cockpit-podman.spec.in
- packit.yaml
- test/vm.install
Ported most commits from https://github.com/cockpit-project/starter-kit/pull/488 , except for the one that actually rebuilds the webpack during RPM. We don't currently have pressure to do this for existing projects, and with the commits from these PRs (and thus having node cache tarballs available for releases), we could enable this quickly if/when needed.
> Build node cache on release, move to xz release tarballs

- Makefile
- cockpit-podman.spec.in
In particular for the [hardlink in release tarballs](https://github.com/cockpit-project/cockpit-machines/issues/379)
> Maintenance updates, starter-kit backports

- .eslintrc.json
`var` has broken/unexpected scoping in JavaScript, and can lead to
subtle errors. It's preferable and safer to use `const` whenever
possible, and `let` where necessary.
There are no usages of `var` in our code nor the imported parts of
cockpit's pkg/lib right now, so just enable the rule to ensure that it
stays that way.
Cherry-picked from starter-kit commit 49a3d58e82.
> eslint: Enable no-var rule

- packaging/debian/watch
This was forgotten in commit 0225c84a8661.
---
Now it works again:
```
❱❱❱ uscan --report
uscan: Newest version of cockpit-podman on remote site is 35, local version is 34
uscan:  => Newer package available from:
=> https://github.com/cockpit-project/cockpit-podman/releases/download/35/cockpit-podman-35.tar.xz
```
> packaging: Move Debian watch file to xz compressed tarballs

- src/ImageRunModal.jsx
Resolves the react warning that every child needs to have an unique
prop.
> Set key for children for the DynamicListForm

- .github/deploy-keys.sh
These deploy keys were created manually so far. Let's keep them in a
shell script so that we don't need to remember which ones we need, and
how to re-generate them en masse if/when we need to.
cockpit-podman currently just uses one deploy key, but other projects
have a lot more. Write it in a generic way, so that it will look similar
in other projects.
-----
I ran the script with my own token, and it deplaced the secret key on https://github.com/cockpit-project/cockpit-podman-weblate/settings/keys and the public key on https://github.com/cockpit-project/cockpit-podman/settings/environments/267165291/edit with my own (the previous one was generated by @allisonkarlitskaya ). I [manually ran the pot refresh workflow](https://github.com/cockpit-project/cockpit-podman/runs/3836593135?check_suit …
> Add script to (re-)generate GitHub deploy keys

- .github/workflows/weblate-sync-pot.yml
- README.md
This is mostly an excuse to check how packit is doing on fedora-{34,rawhide} -- I expect this to be fully green now.
> Small fixes

- test/check-application
An superuser has the option to delete his or users images, test both
options in a new test so we have images to prune.
> test: Add test for selection options when pruning

- package.json
This depends on "coa", which recently got a trojan horse:
https://github.com/advisories/GHSA-73qr-pfmq-6rp8
As it's not being used at all, just drop it.
> npm: Drop unused svgo dependency

- src/PruneUnusedImagesModal.jsx
Drop empty div's created by FlexItem as they are not required.
"Indent" the list of unused images so it's visually on the same level
as the checkbox text. Lastly add `aria-owns` to define the list as a
child of the checkbox.
> Prune Unused Images style fixes

- package.json
That latest version has a grave regression:
TypeError: Error while loading rule 'jsx-a11y/alt-text': rule.create is not a function
Downgrade back to 6.4.1 for the time being.
See https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/824
---
This just [broke the release](https://github.com/cockpit-project/cockpit-podman/runs/4162488559?check_suite_focus=true). c-machines is affected as well.
> npm: Avoid broken eslint-plugin-jsx-a11y 6.5.0 version

- package.json
Version 6.5.1 got released which works with ESLint 7 again and fixes
[1]. Bump the dependency. This essentially reverts the hack from
commit 195979e0e.
[1] https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/824
> npm: Update to latest eslint-plugin-jsx-a11y

- Makefile
- src/PruneUnusedImagesModal.jsx
As per design, let the system/user images stand out when pruning as an
administrator. As in https://github.com/cockpit-project/cockpit-podman/pull/799#issuecomment-948586523
> Make the system/user text bold in unused images

- test/check-application
Removing running container takes longer and if we timeout we often
don't let podman cleanup bound ports which makes subsequent tests to fail.
This is common issue we had. It can be reproduced like this.
1. Add something which makes tests to fail:
```diff
diff --git test/check-application test/check-application
index 1cc0f7e1..e32d4be8 100755
--- test/check-application
+++ test/check-application
@@ -1383,6 +1383,7 @@ class TestApplication(testlib.MachineCase):
self.assertIn('8001/tcp:[{ ', ports)
self.assertIn('9001/tcp:[{127.0.0.2 ', ports)
self.assertNotIn('7001/tcp', ports)
+        b.wait_visible("#foo")
env = self.execute(auth, "podman exec busybox-with-tty env")
self.assertIn('APPLE=ORANGE', env)
```
2. `./test/common/run-tests TestApplication.testRunImageSystem …
> test: Don't timeout on cleanups

- src/ImageRunModal.jsx
- test/check-application
When a user tries to create a container of which the port is already
used the container doesn't start and is not removed. If the user
corrects the host port and clicks create again the container won't be
created as the name is already in use so removed it on error.
> Remove created container if it doesn't start

- Makefile
The shell DOM changed in Cockpit 258. Pick up the Browser.logout()
change which can deal with both old and new shell versions.
> Bump cockpit test lib to fix Browser.logout() for cockpit 258

- test/vm.install
Our ubuntu-stable image is 21.04 now, so drop the now unused backports
installation.
Drop the runc/crun hack, that bug got fixed a while ago.
> test: Drop obsolete vm.install hacks

- test/vm.install
Since https://github.com/cockpit-project/bots/commit/b06bd37b0ad our
Debian/Ubuntu test VMs have the basic cockpit packages pre-installed.
Drop the apt calls to install them, so that we stop getting surprise
breakages due to new cockpit versions. These will now properly appear on
image refreshes.
> test: Drop installing basic cockpit packages on Debian/Ubuntu

- src/ImageRunModal.jsx
- test/check-application
Podman users might have file or a list of environment variables they
want to add to a new container. As adding them one by one is quite
cumbersome handle inserting FOO=bar and multiple lines of such formatted
env variables.
Closes: #816
> Allow inserting multiple environment variables

- Makefile
This will fix the tests when running against cockpit 259, where the
shell got changed to not render the `#machine-reconnect` button all the
time any more.
This should fix broken rawhide tests
> Bump test/common API to 259

- src/ImageRunModal.jsx
- test/check-application
When a user clicks on the cpu shares / memory limit input automatically
enable the corresponding checkboxes. For a <FormSelect> the onFocus
method does not trigger when a user clicks on it, making it impossible
to enable the checkbox.
Closes #849
> Enable checkbox when input is focussed

- src/Containers.jsx
- src/ImageRunModal.jsx
- src/ImageRunModal.scss
- src/Images.jsx
- src/app.jsx
- src/podman.scss
- test/check-application
Implement the option to configure a restart policy for containers, the
default is no restart policy which means the container exits.
'on-failure' means it's restarted when the container exists with a
non-zero exit code for a maximum of retries. Always means it is always
restarted, to make this work on reboot the podman-restart service needs
to be enabled. For user containers this means `loginctl enable-linger`
has to set if a user wants his container to start without logging in
after a reboot.
---
For system containers it is now possible to set a restart policy for new containers.
> Add restart policy to create new container

- src/Containers.jsx
- src/ImageRunModal.jsx
- test/check-application
This adds the ability to create a new container in a pod group, a
container cannot be moved out or into a pod once it has been created.
Closes: #487
---
It is now possible to create a container in an existing pod using the `Create container in pod` button.
Create container dialog now shows in which pod the container is created
> Create a container in a pod

- test/check-application
Ubuntu 21.04 should support cgroups v2 now:
root@ubuntu:~# grep cgroup /proc/filesystems
nodev	cgroup
nodev	cgroup2
> test: Enable cgroups v2 tests on ubuntu-stable (21.04)

- src/Containers.jsx
- src/PodActions.jsx
- src/util.js
- test/check-application
Bring containers to the similiar feature parity to podman pods by adding
pause/resume options. Also make the order of the menu options the same
for pods and containers and add "Force restart" to the pod actions.
> Add pause/resume to containers

- src/ContainerLogs.jsx
- src/ContainerTerminal.jsx
The calculation for the padding in the card and table was incorrect
leading to the table headers to "jump" when switching between details
and logs as the terminals does not fit in the card.
> Fix jumping headers in container details

- src/Containers.jsx
- src/ImageRunModal.jsx
- test/check-application
With the commit 107f060 this.state.isSystem was referenced with it being
initialized. This was never caught in our test setup as we never
explicitly login as root and then fallback to the admin's podman socket.
> Fix regression this.state.isSystem undefined

- Makefile
With image-customize now processing its arguments in the given order
[1], we can do the rawhide upgrade and the other VM preparation in one
step. This saves a now unnecessary shutdown/reboot.
[1] https://github.com/cockpit-project/bots/commit/78e199f600f
> Merge image-customize calls for rawhide scenario

- src/Images.jsx
- src/podman.scss
- Don't use a Flex to group button and menu, this avoids some extra
space between the button and the menu.
- Don't give the actions column a title, this avoids some extra space
between the first field and the menu in mobile layout.
- Let the image name be broken at every character, this prevents the
table from being wider than its container at certain widths.
- Move the "Create container" button into the menu in mobile layout.
This is done by always having both button and menu entry in the DOM,
and only showing one of them as appropriate.
- Take control over the card header layout, so that the actions stay
in the top-right corner.  Also, the title stats stay together as
long as possible.
Fixes: #864
New pixel test references: https://github.com/cockpit-project/pixel-test-reference/compare/ …
> Images: Improve mobile layout

- Makefile
- test/vm.install
This centralizes/factorizes the rpm/deb/arch package builds, and now also
builds RPM packages in the VM instead of on the host, which is cleaner.
Drop the `make srpm` rule, as it's not very useful. Keep the `make rpm`
rule, as sometimes developers do this manually. This might be replaced
later on with another image-customize feature which copies the built rpm 
out of the VM. 
----
Dependencies:
- https://github.com/cockpit-project/bots/pull/2875
- https://github.com/cockpit-project/bots/pull/2876
> Use image-customize --build to build/install distribution packages

- Makefile
Our recent tasks container refresh updated Chromium from 94 to 96, which
changes the pixels a bit.
[pixel diffs](https://github.com/cockpit-project/pixel-test-reference/compare/44585b3d10aebacd9d543c3efbb72e4d77102e32..a82718624031fc91eec3ddf0f90b110f29d38a0e)
> test: Update pixel references for Chromium 96

- src/ImageRunModal.jsx
The exception object has no reason member.
On aarch64 it now shows:
Since podman does not have any error codes this is the best what we can show.
> Display error details for pulling the image

- test/check-application
We only create container and not start it. This status makes more sense
in general. It must have been updated in v4.
FWIW https://github.com/containers/podman/commit/1ef96364fe
It seems that there is precedence for mapping configured to created.
> test: Accept 'Created' for not started containers

- test/browser/browser.sh
Commit e626b72074f accidentally dropped setting `$LOGS` to an absolute
path if `$TMT_TEST_DATA` is not set. This causes the test to fail with
test/browser/run-test.sh: line 75: logs/exitcode: No such file or directory
when running against older `tmt` versions. This is the case on the
internal RHEL testing farm, but not on the public Fedora/CentOS one
(which is why we didn't see this in packit).
> tmt: Put back absolute log path for older tmt versions

- src/ImageRunModal.jsx
- src/app.jsx
The expected indentation of self-closing tags and closing parentheses
became stricter with current eslint-plugin-react versions.
---
See e.g. [this failure](https://logs.cockpit-project.org/logs/pull-3009-20220227-024922-aa8d8db8-ubuntu-stable-cockpit-project-cockpit-podman/log.html) in https://github.com/cockpit-project/bots/pull/3009 or https://github.com/cockpit-project/bots/pull/2960
> Reformat code for eslint-plugin-react 7.29.x

- .gitignore
- Makefile
- packaging/cockpit-podman.spec.in
- test/browser/browser.sh
Tested by `make update-po`, adding German translations locally, `make install DESTDIR=/tmp/x` and inspecting /tmp/x/usr/share/metainfo/org.cockpit-project.podman.metainfo.xml . This works fine.
After that lands, and the next POT refresh, I'm happy to add the translations to weblate.
> Port AppStream i18n from starter-kit

- src/ImageRunModal.jsx
- src/ImageRunModal.scss
- test/check-application
Align the podman create image design with the in progress machines
dialog redesign. The owner option is now moved to the details tab and
changed to a radio button so it's more clear it's a form option. The
container name input can now take up the full input which is nicer on
mobile devices.
---
> Move Owner option to Details tab

- test/check-application
This still has a too old criu (inherited from Debian testing).
- Requires new image: https://github.com/cockpit-project/bots/pull/3131
> test: Adjust for ubuntu-2204

- Makefile
- packit.yaml
- test/vm.install
All our test images now pull the requires podman test images during
image creation.
> Makefile: run tests fully offline

- cockpituous-release
All our other projects release to that. For a user it does not make too
much sense to have each project in its own COPR. All Cockpit packages
have similar QA standards, after all.
> cockpituous: Build in cockpit-preview COPR

- test/check-application
Should address [this failure](https://logs.cockpit-project.org/logs/pull-3227-20220411-220701-f3ad8f1b-fedora-36-cockpit-project-cockpit-podman/log.html) and similar ones (see long test failure history below). Blocking image refresh in https://github.com/cockpit-project/bots/pull/3227
> Test fixes

- Makefile
- test/vm.install
In particular, this will lower the default browser wait timeout from 60
to 15 seconds [1].
[1] https://github.com/cockpit-project/cockpit/pull/17192
> Bump cockpit's lib and test API to 268.1

- src/client.js
Most functions in client.js wrap a promise around a podmanCall which is
already a promise.
Just noticed this occurs a few times in a new PR, I've also been guilty of doing such copy pasta so let's clean it up.
> Don't wrap a promise with a promise

- packit.yaml
Since we moved SRPM builds from sandcastle to COPR, there is no need any
more to do this development/magic options hack.
> packit: Simplify upstream PR tarball build

- src/ContainerRenameModal.jsx
- src/Containers.jsx
- src/app.jsx
- src/client.js
- test/check-application
Allow to rename a container, if it is not running or paused.
There is an issue with container not being refreshed after renamed, as no rename event is fired. This should be fixed in podman v4.1 according to https://github.com/containers/podman/issues/13919
> container rename support

- src/Images.css
When I tried to prune images, the mouse didn't change to make it look clickable and it didn't work as expected. It turned out there were no images to prune, so we should not restyle the color to a danger state when it's disabled.
I have it skip recoloring menu items that are either pf-m-disabled and/or using the PF aria disabling class.
> images: Do not danger-ify disabled menu items

- Makefile
Starting any podman container fails in RHEL 8.7 due to
https://bugzilla.redhat.com/show_bug.cgi?id=2086757 . Install the
missing package manually for the time being until this gets fixed.
> test: Adjust for rhel-8-7

- src/ContainerHeader.jsx
- src/app.jsx
- test/check-application
Since Cockpit 269 the service top CPU usage lists podman containers and
links to the podman page without filtering on a specific container name.
For users it would be more useful if they could directly spot the
container, the newly introduced url parameters can filter based on owner
and a search string.
> Support url parameters for filtering

- Makefile
- src/ContainerHealthLogs.jsx
- src/Containers.jsx
- src/Containers.scss
- src/ImageRunModal.jsx
- src/app.jsx
- src/client.js
- src/podman.scss
- test/check-application
Fixes #345
One known limitation is reported in https://github.com/containers/podman/issues/13083
TODO - if image has healthcheck defined, prefill the values
---
It is now possible to set up, inspect and trigger health checks for container. Also the most recent history as well as overall status are presented.
> Support healthcheck

- Makefile
- test/check-application
- test/vm.install
The intermediate images were the previous versions of the images which
`podman pull` in test/vm.install updated. That was a time bomb, as
sometimes there would be a new version and sometimes not.
Now that we never refresh the images any more during tests, these
transient intermediate images should be gone.
This reverts commit fb0437f5045cd03346d16b282235ce7bc7a233b4.
---
Spotted by/blocks https://github.com/cockpit-project/bots/pull/3437
> Revert "test: Adjust tests for coreos", run tests offline

- Makefile
See https://github.com/cockpit-project/cockpit/pull/17429 . This fixes
tests with Firefox version 101.
> Pick up cockpit test API fix for Firefox 101

- .github/workflows/release.yml
Unmodified copy from cockpit.git. Copying this is a bit awkward, but
let's discuss how we can share these (composite actions or otherwise)
without time pressure.
> workflows: Tag our releases in node-cache

- .github/workflows/release.yml
tools/node-modules are not defautly present on cockpit-podman. Instead
they should be fetched from cockpit repository.
This is a clone of https://github.com/cockpit-project/cockpit-machines/pull/736
> Fetch tools/node-modules in release workflow

- Makefile
commit c06bf5cfd6c8 had the unintended side effect of including
node_modules/ into the dist tarball, as `git ls-files` now includes
`node_modules. This made the tarball balloon from 0.8 to 65 MB, and make
`tar` take ages to compress.
Explicitly ignore the directory.
----
Compare the tar size for [49](https://github.com/cockpit-project/cockpit-podman/releases/tag/49) to [48](https://github.com/cockpit-project/cockpit-podman/releases/tag/48).
I noticed this when trying to package the new releases for Debian. It took painfully long to process the tarball, and I got a gazillion lintian warnings about the unaccounted files in n_m/. After this I'd like to tag a 49.1.
> Re-drop node_modules from release tarballs, Include Cockpit repo files in release tarballs

- packit.yaml
tmt 1.14.0 can finally discover tests from the dist-git source, instead
of having them to checkout from upstream git.
https://src.fedoraproject.org/rpms/cockpit-podman/pull-request/37
dropped the hardcoded `ref:`, so we can drop all that hackery.
> packit: Drop FMF hack, enable downstream job notifications

- package.json
This release contains a fix for nodejs to prefer ipv4 resolving which
is needed as Firefox the CDP runs only on ipv4 on Fedora rawhide on
packit.
> package.json: Update chrome-remote-interface

- .github/workflows/reposchutz.yml
Verify the commits in the node_modules repository using the similiar
workflow as cockpit's with a small adjustment to checkout the
tools/node-modules script.
Tested it with a my main:
https://github.com/jelly/cockpit-podman/runs/6972626867?check_suite_focus=true
And broke it:
https://github.com/jelly/cockpit-podman/runs/6972679595?check_suite_focus=true 
If this is correct, I'll make a similar PR to cockpit-machines.
> .github: add reposchutz workflow

- .github/workflows/reposchutz.yml
Instead of relying on COCKPIT_REPO_STAMP which changed in
fca470b5135228fcd8865 use the existing make target.
> .github: don't depend on COCKPIT_REPO_STAMP target

- src/rest.js
- test/check-application
Maximum length on one message is 4096 characters. When the reply is
longer than that it will come in multiple messages. In such case we need to
connect them before trying to parse such message.
This for example happens when there are multiple containers and `Stats` often
are split into multiple messages.
Fixes #1025
> Reply from REST can come in pieces

- test/browser/browser.sh
- test/check-application
testLifecycleOperationsUser flakes in CI where the CPU statistics are
available but the memory statistics are not yet. So wait on both to be
available.
Examples:
https://cockpit-logs.us-east-1.linodeobjects.com/pull-1039-20220718-145652-17708f5b-arch/log.html#16-2
https://cockpit-logs.us-east-1.linodeobjects.com/pull-1017-20220715-090657-252dda76-arch/log.html#16
> test flake/failure fixes

- test/check-application
pgrep does not have an `-e` option. "echo" conceptually only makes sense
for pkill, as pgrep's raison d'être is to show the pids..
> test: Fix pgrep invocation

- src/PruneUnusedImagesModal.jsx
- test/check-application
Check if the user or system service is avaiable instead of checking if
both are true. Which does not work as userServiceAvailbe is null when
logging in as root.
Closes #1022
> Fix system logic in prune unused images dialog

- test/browser/run-test.sh
Commit c22bb7121cd73324e broke running tests for tarball releases [1].
Bring back the `npm install` for the non-git case.
Clean up the pointless `git init` and make the dot-git moving
conditional on the presence of .git (i.e. testing an upstream PR).
[1] https://src.fedoraproject.org/rpms/cockpit-podman/pull-request/53
---
I'll do a 50.1 release after that, to fix the [gating test failure](https://artifacts.dev.testing-farm.io/4e2af3c2-3e7f-4111-8439-2fadbcfffdbc/).
> fmf: Add non-git fallback for npm module installation

- Makefile
We want to move bots API from deprecated scp to rsync. rsync uses
trailing slashes to tell apart copying a directory as a different name
in the target (trailing slash) from copying a directory *into* the given
target path (no trailing slash). Here we want to do the former.
---
This blocks https://github.com/cockpit-project/bots/pull/3640
> Makefile: Use rsync-friendly directory path

- src/ContainerDetails.jsx
- src/ContainerIntegration.jsx
- src/Containers.jsx
- src/client.js
- test/check-application
Following conversation in #923 this adds new tab in container details
which shows ports, mounted volumes and filtered environment variables.
I decided someone might find it useful to check all env variables so I've added `Show more` button which shows all variables.
---
Published ports, mounted volumes and environment variables are now visible in container integration tab.
By default only variables set by user are shown and after clicking `Show more` all variables are visible.
> Add Volumes and Env Variables to container details

- package.json
- src/ImageRunModal.jsx
- src/ImageRunModal.scss
Styles for this input count on some given minimum width. But the way we
use it with `pf-m-3-col-on-md` breaks that.
Fixes #1054
> Don't overlap host path with other elements

- Makefile
- test/browser/main.fmf
- test/browser/run-test.sh
This avoids having to run `npm`, and thus a potentially brittle internet
access, during FMF test runs. It also avoids the npm test dependency,
which tends to be uninstallable in Rawhide.
We have successfully used this approach in cockpit for a long time.
----
Avoids [this failure](https://artifacts.dev.testing-farm.io/b3b0d33e-b8f6-4cb5-80da-5a94c5a07095/), which has been going on for a week [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2110750). This already hit us in the past.
By and large the same as https://github.com/cockpit-project/cockpit-machines/pull/784
> Ship npm integration test dependencies in dist tarball

- src/ContainerIntegration.jsx
- test/check-application
Read-write volumes use left-right arrow,
Read-only volumes use right arrow.
Both arrows have a tooltip:
> Show volume permission in container integration tab

- .flake8
- Makefile
This is easier to use, more flexible as pycodestyle errors can be
overridden on specific lines, and IDEs/vim-ale can read .flake8 and stop
complaining about the line length.
> test: Move to flake8

- test/check-application
Running `a && b` is wrong for our intent here, as it will silently
succeed if `a` fails, and never run `b`. This can often cause follow-up
failures which are harder to investigate.
This was solved in in https://github.com/cockpit-project/bots/pull/3706
by running all Machine.execute() commands with `set -e`.
Replace `&&` with `;`, use Machine.write() to write files, and drop the
redundant `set -e` call (we don't care about the `-u`, that shell script does
not have any variables).
> test: Robustify executed commands

- src/ImageHistory.jsx
- src/Images.jsx
- src/client.js
- src/podman.scss
- test/check-application
A new History tab has been added to the images view which fetches the
history on demand.
The comment field always seems to be empty.. and therefore cut off.
@garrett please take a look:
On Mobile
On tablet
> Show image history

- src/app.jsx
- test/check-application
Podman does not send a pod event when a container in a pod is removed,
so the only we have to force reload the pod state after a containe
removal.
Fixes #1075
> Reload pod state after container removal

- packit.yaml
As usual, keep supporting the two most recent branched versions.
Also drop Rawhide from our cockpit-preview COPR build: We directly
upload new releases to Rawhide anyway, so this is redundant.
----
I already reconfigured our [preview repo](https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/) accordingly.
> packit: Drop Fedora 35, add Fedora 37

- test/check-application
To make it easier to assert the amount of images which should be shown in the UI, so adding a new container image to the test image does not require us to change all our tests.
> test: obtain image count in setUp

- test/check-application
When pruning only root images, count the actual root images as root and user images are not always equal. When pruning a selection of images, don't hardcode the root images number.
> test: fix test image calculations

- src/Containers.jsx
- src/app.jsx
- test/check-application
Fixes #980
---
Cockpit-podman now shows all containers by default.
> Show all containers by default

- test/check-application
based on how many got deleted.
This matters with a recent rhel-9-1 refresh: https://cockpit-logs.us-east-1.linodeobjects.com/pull-3861-20220914-064245-a4a883db-rhel-9-1-cockpit-project-cockpit-podman/log.html
> test: Also compute number of images that root sees

- src/ContainerIntegration.jsx
- src/Containers.jsx
- src/Containers.scss
- src/podman.scss
- test/check-application
Show the port details of a pod using a popover.
---
Podman now shows the CPU and memory usage of a pod. The amount port and volume mappings of a pod are now shown with a popover showing the exact detailed mapping.
> Show pod details

- src/Containers.jsx
There should only be one primary action button per page ideally.
> Make "Create container in pod" secondary

- src/ContainerRenameModal.jsx
- src/Containers.jsx
- src/DynamicListForm.jsx
- src/DynamicListForm.scss
- src/ImageRunModal.jsx
- src/ImageRunModal.scss
- src/PodCreateModal.jsx
- src/PublishPort.jsx
- src/Volume.jsx
- src/client.js
- src/util.js
- test/check-application
- test/vm.install
- Allow to create new pods with port mappings - new kebab control on containers panel
- Show pod owner in listings - under pod name
- Correctly limit container ownership when creating container in existing pod - select owner according to pod and disable owner selection
> Create Pod Functionality

- src/app.jsx
Podman now has the podId in the remove and start event, so we can only reload data for a specific pod only. This feature is still in podman main and 4.3.0-rc1.
https://github.com/containers/podman/issues/15408
> Handle podId in container events

- src/Containers.jsx
Podman reports 0 CPU and ram back for non-running containers, due to our code we show 0.00% CPU and no ram. Make this experience consistent and just only show CPU/RAM for running containers, this also fixes a pixel flake where one container did show CPU and the other not.
Note: probably requires a pixel test update...
> Don't show CPU stats for exited containers

- Makefile
- test/check-application
Cockpit now disallows root login by default, to allow it in tests bump testlib and pass `enable_root_login` so the `disallowed-users` file is emptied.
> test: enable root login for tests

- src/ContainerCheckpointModal.jsx
- src/ContainerRestoreModal.jsx
- test/check-application
Ideally we would also test the TCP connection / MAC and IP related checkboxes on restore, but from a small test:
```
cat /sys/class/net/*/address
```
The MAC address does not really change, and we can't change it with the alpineimage as it has no.
Turns out while making this PR I realised we have a busybox image which has `ip`
But reading the man page.. we need to create a container with `--mac-address` and `--ip` to test this functionality. This can be done but from my testing it seems to be broken?!
```
podman run -dit --mac-address 92:d0:c6:0a:29:38 --name fo busybox:latest sh
```
```
podman container checkpoint fo
```
```
podman container restore --ignore-static-mac fo
```
```
podman inspect --format '{{.NetworkSettings.MacAddress}}' fo
```
```
[root@fedora-37-127-0-0-2-2201 ~]# …
```
> Checkpoint restore fixes

- src/Containers.jsx
- src/app.jsx
- src/util.js
During restart container's State is still "running" and console was getting disconnected but not reconnected. Additional flag was added to keep information about restart and connect channels again.
Closes #1089
> Reconnect console after container restart

- .github/workflows/reposchutz.yml
The podman version (3.4.4) on Ubuntu 22.04 has issues with pipes and stops before piping the full tarball over (at ~ 25M of ~ 250M). This makes the protection checks fail, which means we can't land node_modules updates. For now pin it to 20.04 until we figured out the issue on 22.04.
Tested this on my own fork but already nuked the main branch. Run can be observed here:
https://github.com/jelly/cockpit-podman/actions/runs/3649718893/jobs/6164758702#step:3:404
> .github: run protection checks on Ubuntu 20.04

- src/Images.jsx
This has two advantages - it is less jumpy when filter hides all images as well as it fixes highlighting on newly added images.
> Keep 'Hide images' toggle even when filtering out all images

- packaging/cockpit-podman.spec.in
https://github.com/containers/crun/issues/1091
> packaging: workaround missing crun dependency on criu-libs for libcriu.so.2

- packaging/debian/watch
The /releases page has become JavaScript-y recently and thus unreadable by machines. Scan the API instead and construct a download URL.
----
Same change as in https://github.com/cockpit-project/cockpit/pull/18048 . I can use the exact same file, due to the handy `@PACKAGE@` macro.
```
$ uscan --report --verbose
uscan info: Found the following matching hrefs on the web page (newest first):
https://github.com/cockpit-project/cockpit-podman/releases/download/58/cockpit-podman-58.tar.xz (58) index=58-4 
https://github.com/cockpit-project/cockpit-podman/releases/download/57/cockpit-podman-57.tar.xz (57) index=57-4 
https://github.com/cockpit-project/cockpit-podman/releases/download/56/cockpit-podman-56.tar.xz (56) index=56-4 
[...]
uscan: Newest version of cockpit-podman on remote site is 58, …
```
> packaging: Use GitHub API in debian/watch

- test/check-application
The page is utterly slow, and sometimes takes longer than 15s to load on a busy machine.
---
See https://cockpit-logs.us-east-1.linodeobjects.com/pull-1169-20230103-181159-45c8d761-arch/log.html#20-2
> test: Increase wait timeout for Services page

- .github/workflows/release.yml
Copy pasta from commit e6edcb6a8.
> .github: Fix typo in release workflow

- packaging/cockpit-podman.spec.in
See https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
Also see 9bb49fe1c4d027a37eab61e8a2b187ffef168a2d in cockpit.
> packaging: Migrate spec to SPDX license

- src/ImageRunModal.jsx
- test/check-application
We prefilled always `sh` as command for new containers but this is wrong. We should always use default command from image. There are multiple changes:
1. Don't offer 'sh', just leave the command field empty
2. If user selects local image prefill the command from image
3. If user selects remote image leave the command input empty
4. If we preffiled the input in 2. and user unselects the image with (x) remove the command if it is still the same
5. If user touches the command all of the above are not applied
Fixes #1126
> Prefill command from image

- test/check-application
We see in tests often messages like:
`WARNING: Waiting for !ph_is_present("#table-pod-1") took 10.6 seconds, which is 70% of the timeout.`
In current run there are 18 of those, which means we wait for 3 minutes longer than we need to.
[test run before these changes](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1155-20230116-102954-0f64fa41-fedora-37/log)
> tests.speed++

- test/check-application
In 3779bb5fc32fb80f4c1bb3 we now start containers with --stop-timeout 0, so this can be dropped.
But let's let the bot check!
> test: drop test extended timeout for testCreatePodUser

- test/reference-image
The tasks container is Fedora 37 already.
> test: bump reference-image to fedora-37

- HACKING.md
- Makefile
- test/check-application
That transition has happened several years ago. Let's stop supporting
switching to cgroupsv1 on Fedora, nobody else tests this any more
anyway. Let's just test whatever the OS defaults to. 
This was the only destructive test, and didn't even do anything useful
on all OSes except Fedora. Move `@nondestructive` to the class.
> test: Drop explicit cgroupsv1/v2 tests, change default TEST_OS to fedora-37

- src/ContainerLogs.jsx
This endpoint sends binary data -- at least the 8 byte header (which the code strips off), but also the console logs could very well have ASCII control characters and such. The Python bridge decodes text channels a little differently than the C bridge; this fixes container logs with current Python bridge.
---
This does not fully fix the pybridge tests yet, but it fixes [four failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1196-20230201-130504-b48aaae7-fedora-37-pybridge/log.html); the last one is `testNotRunning` ("only" unexpected messages), but I'm investigating that in #1196
> Open /logs in binary mode

- test/check-application
The journal error in `testNotRunning` looks a little different with the
Python bridge.
----
Investigating the remaining failures. Locally, the tests now by and large pass for me.
> test: Add expected message for Python bridge

- test/check-application
This was broken in 4.0 and now fixed in 4.4 which is still an release candidate. Locally this has been tested with podman-4.4.0~rc1.
Closes #1179
Locally tested with https://koji.fedoraproject.org/koji/buildinfo?buildID=2111508 and Fedora-37
> test: test ignore MAC Address on restore feature

- HACKING.md
- Makefile
- package.json
- packaging/debian/copyright
- src/util.js
- test/browser/browser.sh
- webpack.config.js
Cockpit recently changed to an ESM build system [1]. Bump COCKPIT_REPO_COMMIT to that and follow suit.
This does not work with old node.js 10 any more which is still the default in RHEL 8. Install the newer version 16 instead.
[1] https://github.com/cockpit-project/cockpit/pull/18366
----
Pretty much identical to https://github.com/cockpit-project/starter-kit/pull/625 except for the node_modules submodule refresh.
> build: Move to a webpack module, generalize bundler language/variable names

- src/ContainerCheckpointModal.jsx
- src/ContainerCommitModal.jsx
- src/ContainerDeleteModal.jsx
- src/ContainerDetails.jsx
- src/ContainerHeader.jsx
- src/ContainerHealthLogs.jsx
- src/ContainerIntegration.jsx
- src/ContainerRenameModal.jsx
- src/ContainerRestoreModal.jsx
- src/Containers.jsx
- src/Dropdown.jsx
- src/DynamicListForm.jsx
- src/ForceRemoveModal.jsx
- src/ImageDeleteModal.jsx
- src/ImageDetails.jsx
- src/ImageRunModal.jsx
- src/ImageSearchModal.jsx
- src/ImageUsedBy.jsx
- src/Images.jsx
- src/Notification.jsx
- src/PodActions.jsx
- src/PodCreateModal.jsx
- src/PruneUnusedImagesModal.jsx
- src/PublishPort.jsx
- src/Volume.jsx
- src/app.jsx
Otherwise we rely on treeshaking mechanisms to remove unused code, thus making our bundle size more vulnerable to bundler's ability to drop dead code.
> Use whole path in patternfly imports

- Makefile
This is needed for the container prune feature which requires the ability to select all unused containers.
> Makefile: bump Cockpit lib for onHeaderSelect

- src/ContainerCommitModal.jsx
- src/ImageRunModal.jsx
- src/ImageSearchModal.jsx
- src/PodCreateModal.jsx
Fixes #1221
Moved dialog errors at the top in these components.
1. ImageRunModal
2. PodCreateModal
3. ImageSearchModal
4. ContainerCommitModal
> fix: show dialog error at the top

- src/ImageRunModal.jsx
When creating a container with the system session offer a popover with the differences between the owner types.
Closes: #1067
---
> Explain the difference between a user and system session

- src/ContainerLogs.jsx
- test/check-application
Since we use a binary channel for the rest API the errors are not strings so we have to decode them and extract the error message.
Closes: #1237
> Decode Uint8Array into a string and extract the error message

- Makefile
- build.js
See https://github.com/cockpit-project/cockpit/pull/18550
This also brings in some PF cleanup to fix spacing between modal
footers. Adjust pixel tests accordingly.
---------
[pixel test review](https://github.com/cockpit-project/pixel-test-reference/compare/df8b4183e267b5d1b92b420dbcbcf2d73cf3f690..d35af163f6f13123a1e95855481606f6aa92e354)
> Bump Cockpit lib for esbuild plugin updates

- Makefile
- build.js
- package.json
This introduces the override for breakpoints, therefore pixel test updates are required.
> Reuse esbuild configuration with main cockpit project

- plans/all.fmf
- test/browser/browser.sh
- test/browser/main.fmf
- test/browser/run-test.sh
A single run already takes half an hour if all tests pass, and a full hour if there are many failures. That's massively longer than the < 10 mins that they take on our upstream CI.
Split the tests into three parts and run them in parallel plans.
----
Comparison with recent single-plan runs: [c8s](https://artifacts.dev.testing-farm.io/7590103b-29d0-4deb-98c3-69f3f2a5010e/) took 29 min ; [F38](https://artifacts.dev.testing-farm.io/9584be6a-c8be-4063-ac93-85675fefe8c4/) took 27 min (pipeline.log) The tests here take between 16 and 21 mins, so about 33% to 50% less.
> fmf: Split into three plans

- test/check-application
Our normal test timeout is 15, for restarting containers the timeout of 5 is not enough and it flakes occasionally.
context: https://github.com/cockpit-project/cockpit-podman/pull/1241#issuecomment-1488363794
Be aware, we have more flakes, but let's tackle them off one by one
> test: don't lower test timeouts to 5

- test/check-application
The third parameter of write_file is append but instead we want to invoke a post restore action.
> test: correctly restore root login on ostree

- src/Containers.jsx
PatternFly deprecated isVertical in favour of the orientation property.
https://www.patternfly.org/v4/components/divider/#divider
> Use orientation instead of deprecated isVertical

- Makefile
- test/browser/browser.sh
- test/vm.install
Replace the duplication of image setup with calling podman-images.setup from bots.
In vm.installll, also check if the expected images are already present, to avoid pulling them again on images which are already rebuilt. Once they all are, we can drop this again, and go back to preparing the VM offline.
See https://github.com/cockpit-project/bots/pull/4585
---
I set myself a calendar event in two weeks to check if all images got rebuilt, and drop the container image fetching agian.
> test: Use bots' podman-images.setup

- src/Containers.jsx
- src/util.js
- test/check-application
Allow the sorting of the container name, owner, cpu, memory and state. This makes containers sortable and leaves pods unsorted but containers in pods can be sorted. Allowing pods to be sorted with containers would be undesired.
---
The podman container section now allows a user to sort on name, owner, CPU, memory and state.
> Make containers table sortable

- Makefile
- packaging/cockpit-podman.spec.in
See https://bugzilla.redhat.com/show_bug.cgi?id=2180520
Turn the pattern make rule into an explicit one, as pattern rules don't support dependencies. We only need it for our single spec file anyway.
Cherry-picked from starter-kit commit 8817969d1.
> packaging: Declare bundled NPM dependencies in spec file

- src/Images.jsx
- test/check-application
The image creation dates vary between test runs, and their wrapping is neither reliably broken into one nor two lines. Since this is not possible to ignore with a selector as it shifts the UI let's just skip the mobile layout which makes these dates wrap.
> Skip mobile layout where pixel testing overview as it's flaky

- build.js
- package.json
Sync with cockpit-machines (https://github.com/cockpit-project/cockpit-machines/commit/00f191f45e2990c861230e79b33e92135b388bb5).
Also fixed no-useless-escape eslint warnings. Taken from https://github.com/cockpit-project/cockpit-machines/commit/e2f0e9fbda60e1adf29b24d764486ec96262f224.
> build.js: esbuild-wasm, build duration, fix sourcemap & no-useless-escape eslint warnings

- .github/workflows/cockpit-lib-update.yml
- .github/workflows/npm-update-pf.yml
- .github/workflows/npm-update.yml
- .github/workflows/reposchutz.yml
- .github/workflows/weblate-sync-po.yml
- .github/workflows/weblate-sync-pot.yml
Like https://github.com/cockpit-project/starter-kit/pull/643 and https://github.com/cockpit-project/cockpit/pull/18668 . The newer ubuntu platform already got tested in cockpit and starter-kit, and most workflows here already had `permissions:`. 
I added `statuses: write`, as the PO workflows have it, too. I'm not sure that we really need it, but it's harmless enough.
I restricted the default token permissions to read-only now. Let's test the lib-update workflow here. [workflow run](https://github.com/cockpit-project/cockpit-podman/actions/runs/4752855378) generated #1275 which looks correct.
> workflows: Update to ubuntu-latest, set explicit permissions for cockpit-lib-update

- test/check-application
The real container images on our VM images change all the time. In particular their creation date may be very recent ("last Monday at 11:00 AM") or older ("2023/03/17"). That changes the table column width and breaks the "history" pixel test. Also, the differing widths of the image IDs and dates cause small column width variation. Finally, all of the actual text was ignored by the pixel test, leaving only the table frame (which isn't very interesting, as it's a standard component).
So all of this makes this a bad use case for pixel tests. Instead, create a dynamic dummy image with predictable layers, date, and content, and check it textually.
---
This blocks https://github.com/cockpit-project/bots/pull/4683 , and we've had this kind of noise for each image refresh many times. I tried for …
> test: Check image history textually instead of with pixels

- src/app.jsx
- test/check-application
Currently containerDetails are deleted when container reaches any other state than "running". Because of this when new container is created or is stopped the Integration tab shows infinite loading until the page is refreshed or the container is started again.
> Fix management of containersDetails

- .github/workflows/cockpit-lib-update.yml
- .github/workflows/weblate-sync-po.yml
Pushing the branch with the default GitHub token prevents the "Protection checks" workflow from running, as the default token can't trigger workflows. Do what we do in c-machines and cockpit and use the new `self` environment [1] to pull/push with SSH instead.
[1] https://github.com/cockpit-project/bots/pull/4720
---
I had to land the last few PO updates like PR #1264 with some "sudo" github force, to skip the required "protection checks" run. Same in PR #1278.
> workflows: Use deploy key for cockpit-lib-update and weblate-sync-po

- Makefile
- README.md
- packaging/arch/PKGBUILD.in
- packaging/cockpit-podman.spec.in
- packaging/debian/rules
/usr is package manager territory, and not even writable on OSTree based systems such as Fedora CoreOS or RHEL Edge. This has been common and good practice in autotools for decades.
You can still override this with `make install PREFIX=...`. Use that in the packaging.
Cherry-picked from https://github.com/cockpit-project/starter-kit/commit/57d7c73d6e32
> Install into /usr/local/ by default

- src/Containers.jsx
- src/Containers.scss
- src/PruneUnusedContainersModal.jsx
- test/check-application
Podman lacked the ability to mass delete stopped or exited containers until recently it introduced `podman container prune`. Podman exposes no new API for this so we filter all containers and display them in a new dialog. The name, created and optionally owner is shown of a container when the user and system session is available.
---
Cockpit-Podman's latest release features a new "prune" dialog for bulk deletion of stopped and exited containers, similar to `podman container prune`. This dialog provides the option to unselect containers while displaying container names, creation dates, and owner information to help ensure the intended containers are selected for deletion.
> Add ability to prune unused containers

- test/check-application
A newer Cockpit has different patternfly classnames prefixed with pf-v5, as updating PF brought up some bigger issues.
> test: add compatibility for Cockpit versions

- src/manifest.json
- test/check-application
Check for the existence of the podman.socket for the Cockpit client scenario.
See https://github.com/cockpit-project/cockpit/issues/18935
> Add manifest conditions

- test/check-application
Debian stable moved to Debian 12, which has podman. We can enable testing there now.
> test: Adjust for debian-stable

- test/check-application
To have a successful ruff run, we will need to reduce the line length to 118 characters. This PR fixes 49 violations, a follow up will be required to complete it but as tests are flaky and we will have many retries let's do it in parts.
> test: reduce line length in tests

- .flake8
- .gitignore
- Makefile
- pyproject.toml
- src/ContainerIntegration.jsx
- test/check-application
We can now start running ruff in CI.
As follow up:
> test: reduce line length to 118 the default in Cockpit

- src/index.html
In the last PF5, we forgot to update the tabular number class.
Pixel test updates https://cockpit-logs.us-east-1.linodeobjects.com/pull-1326-20230703-093916-959ebbfc-fedora-37/log.html
> Update font class for PF5

- test/check-application
That may help to debug failures where containers unexpectedly stop.
---
[example log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1324-20230703-082205-84171830-rhel-9-3/log.html)
> test: Print container logs on failure

- src/Containers.jsx
- src/PodActions.jsx
- src/rest.js
- src/util.js
- test/check-application
Broken out from PR #1324, as these are ready for landing and already help with debugging. That former PR stress-tests testLifecycleOperationsUser. I still saw a [different failure mode](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1324-20230703-134319-67b14112-fedora-37/log.html#26-1) of testLifecycleOperationsUser, but the [primary one](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1322-20230703-061633-7cc9e4bf-fedora-38/log.html#16-1) should be fixed now.
> Fix testLifecycleOperationsUser restart test, add debug logging

- test/browser/browser.sh
This often runs into random DNS/network issues, so retry up to 5 times with exponential back-off.
----
This should alleviate failures like https://artifacts.dev.testing-farm.io/96a81aa0-5fc4-4a8b-80d8-f410310ed0b2/ or https://artifacts.dev.testing-farm.io/420cc043-aa44-4218-8072-bfcdc0179a78/
> fmf: Retry pulling container images

- src/app.jsx
This does not mean that the container goes away, that will only happen for the "remove" event. "cleanup" will also happen (twice!) between "died" and "init" for restarting a container.
This avoids two parallel getContainer() calls with possibly inconsistent information, and generally reduces the number of getContainer() calls.
---
This fixes testLifecycleOperations failures like [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1324-20230703-141527-37092ff0-fedora-38/log.html#26) and [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1324-20230703-141527-37092ff0-fedora-38-devel/log.html#24). [debugging notes](https://github.com/cockpit-project/cockpit-podman/pull/1324#issuecomment-1619493649), stress-tested in #1324
> Don't re-fetch all containers for "cleanup" event

- src/app.jsx
- test/check-application
Don't start pod and container state updates at the same time. They do asynchronous state updates which sometimes step on each other's toes and reverse the real event order.
This mitigates the problem with getting podman API call results in the wrong order (https://github.com/containers/podman/issues/19124); that causes containers to sometimes appear in a non-current state.
-----
See the above podman issue, this can't be perfect. I stress-tested this in #1324, and at least it got a lot better. E.g. in commit 5a28f0d8503bfc6e4845d87733373eed0ac13bc0 I just got one failure out of 5x3x13 runs (amplification x affected retries x TEST_OS). But it makes runs a lot easier to get green.
> Serialize start and remove event handling

- src/ImageSearchModal.jsx
Port ImageSearchModal to a functional component
To simplify using context providers port this component to a functional
component. The only tricky part is that it's not easy to do a state
update with a callback with `useState`. The recommended way is to use
`useEffect` but we can't call onSearchTriggered as that also changes the
state and re-renders causing an infinite loop so we just always pass
selected registry.
Apart from the port to a functional component, this now properly
truncates very long descriptions which take eat up half the search
results space.
Fixes a potential race condition when already having
typed a search entry and then quickly switching the selected registry.
Fallback registries are now properly shown when no search registry was
configured in containers.conf.
> Port ImageSearchModal to a functional component

- src/Containers.scss
The last PF and Cockpit lib update introduced a rather large 24px pod group text.
Closes: #1342
Now looks like:
> Adjust large size of pod ram/cpu stats

- test/check-application
In podman 4.6.0-rc1 the returned exception message is changed and no longer mentions paused/running containers.
> test: adjust pod delete error

- src/Containers.jsx
- test/check-application
The `Pid` property is not exposed in the /containers/ID/json API, and generally not recommended as they can be recycled. We are going to drop `data-pid` in the near future.
Move the restart detection in the test from comparing Pid to comparing StartedAt.
Change the `data-started-at` rendering from Unix time stamp (from /containers/json API) to ISO string (from /containers/ID/json API), as we are going to move to the latter soon, and that also coincides to the CLI output, so it's easier to compare.
> test: Change restart detection from Pid to StartedAt

- src/ContainerCheckpointModal.jsx
- src/ContainerCommitModal.jsx
- src/ContainerDeleteModal.jsx
- src/ContainerDetails.jsx
- src/ContainerHealthLogs.jsx
- src/ContainerIntegration.jsx
- src/ContainerRenameModal.jsx
- src/ContainerRestoreModal.jsx
- src/ContainerTerminal.jsx
- src/Containers.jsx
- src/ImageRunModal.jsx
- src/ImageUsedBy.jsx
- src/app.jsx
- src/client.js
Both the initial container scan and each update called getContainers() once and inspectContainer() twice (!!). But this is very redundant: The objects returned by getContainers() and inspectContainer() have a very similar structure. The latter does not have `Pid` and `PodName`, but we don't use these properties anyway. The others map in a straightforward way:
* `Names[]` → single `Name`
* `Ports` list → `NetworkSettings.Ports` map
* `Mounts` (simple target dir list) →  list of objects with lots of info; direct translation is `.Destination`
* `Started/Exited...At` → `State.*`
* `State` → `State.Status`
* `Command` → `Config.Cmd`
* `Labels` → `Config.Labels`
* `ImageID` → `Image`
* `Image` → `ImageName`
So change the state keeping to call getContainers() only once at initialization, and …
> Eliminate redundant getContainers/inspectContainer calls

- test/check-application
Current Debian and ubuntu-stable images support all functionality. Restrict the test skips to ubuntu-2204.
> test: Clean up test skips

- package.json
- src/ContainerLogs.jsx
- src/ContainerTerminal.jsx
For XTerm 5, use the canvas renderer addon, which was previously built in. The
default renderer uses inline styles and does not work with our strict
C-S-P. Also stop making the Terminal object state. It's completely unnecessary
and may cause unnecessary renders. Adapted from
https://github.com/cockpit-project/cockpit/commit/65471fd9fcb
Don't update to the latest 5.2, as that breaks the a11y tree
(https://github.com/xtermjs/xterm.js/issues/4571). 5.1 works fine.
Note that gettext-parser's current version is 7, but versions ≥ 4 don't
work with our cockpit plugin. That needs to be updated in Cockpit first.
> package.json: Bump most modules

- test/check-application
Test the error conditions, and submitting the rename modal via an enter key.
> test: extend rename dialog test coverage

- src/ContainerDetails.jsx
- test/check-application
Fixes https://github.com/cockpit-project/cockpit-podman/issues/1287
> Show time of container's checkpoint, if any is present

- test/browser/main.fmf
It's not a strict requires, but our tests want to cover checkpoint/restore. podman's crun → criu-libs dependency seems to come and go, and is too indirect to rely on.
-----
Spotted in https://github.com/containers/podman/pull/19500
> fmf: Install criu test dependency

- packaging/debian/rules
This would normally be done during `make clean`, but that is deliberately skipped. Remove LINGUAS to avoid an unclean source after a binary package build.
https://bugs.debian.org/1043810
> packaging: Remove po/LINGUAS during package cleaning

- package.json
Bump dependency of esbuild to fix a dependency issue during install
npm i --package-lock-only
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree npm ERR!
npm ERR! While resolving: podman@undefined
npm ERR! Found: esbuild@0.18.20
npm ERR! node_modules/esbuild
npm ERR! dev esbuild@"^0.18.14" from the root project npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer esbuild@"^0.19.1" from esbuild-sass-plugin@2.12.0 npm ERR! node_modules/esbuild-sass-plugin
npm ERR! dev esbuild-sass-plugin@"^2.10.0" from the root project npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
Closes: #1380
> package.json: bump esbuild

- src/Containers.scss
Fixes #1386
The issue: 
[Screencast from 2023-08-24 10-24-52.webm](https://github.com/cockpit-project/cockpit-podman/assets/108616679/33461de7-c13d-4845-bb59-21f97f2d937d)
This was introduced in https://github.com/cockpit-project/cockpit-podman/pull/1357 as fix as fix for [screen width bug](https://github.com/cockpit-project/cockpit-podman/issues/1319). However it seems that the screen width bug is fixed with `word-break: break-all;`, so using `overflow-x: auto;` seems redundant. Futhermore, the issue it introduced seems bigger than the issue it was originally fixing.
> Fix dropdown's overflow in contains list

- .github/workflows/npm-update-pf.yml
- .github/workflows/npm-update.yml
We moved away from `tools/bots` in 89db1c68a9ff2b2b6f9a55e.
Still fails in my fork, not sure why? https://github.com/jelly/cockpit-podman/actions/runs/6074983559/job/16480217353
> .github: update how to check out bots

- .github/workflows/updates-testing-nightly.yml
Test Fedora with updates-testing nightly every night. When a test fails an issue will be opened.
> .github: add a Fedora updates-testing nightly scenario

- .github/workflows/updates-testing-nightly.yml
It may well happen that nothing has landed on main since the last time the nightly run happened. Disable the "isn't in triggerable state (is: success)" check.
---
This [failed last night](https://github.com/cockpit-project/cockpit-podman/actions/runs/6079229511/job/16491455998) as I already manually triggered it yesterday evening.
I [triggered a run from this branch](https://github.com/cockpit-project/cockpit-podman/actions/runs/6080223985), it succeeded and created a status. It's also visible in this PR, as it's the same SHA that I triggered the workflow on.
> workflows: Force nightly trigger

- Makefile
Slowly we are getting there, sorry I forgot that we have a custom `test/run` per project while I should have known and noted in my PR original Cockpit PR.
> Support the updates-testing scenario in `test/run`

- .github/workflows/nightly.yml
- Makefile
Enable https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next and regularly test against that. While we do have reverse dependency testing against podman itself, we don't yet have it against all the related projects yet, like container-selinux, netavark, or crun.
> Add podman-next scenario

- test/browser/browser.sh
TF runs add the Fedora tag repository with `priority=9`. This breaks upstream reverse dependency tests, as that repository will then win over our "main builds" COPR and thus run tests against a mismatching cockpit-podman rpm.
Counter the hack by dropping the tag repo priority and reinstalling cockpit-podman.
---
See e.g. https://github.com/containers/podman/pull/19953 and all other recent upstream podman PRs, where tests fail like [this](https://artifacts.dev.testing-farm.io/e3b3a2cd-e327-40db-896a-ea6775ef2296/) , because
```
podman-4.7.0~dev-1.20230913192200752553.pr19953.1753.38e069f70.fc38.x86_64
cockpit-podman-75-1.fc38.noarch
```
i.e. this is an outdated Fedora build (not even 76, which is in stable!), instead of the main build.
> fmf: Hack around Testing Farm's tag-repository priority

- pyproject.toml
No code changes necessary, but make sure we don't introduce .format().
> ruff: Enable UP032 f-string rule

- src/Containers.jsx
- src/podman.scss
- test/check-application
> Show toolbox & distrobox containers different in containers listing

- .github/dependabot.yml
- .github/workflows/dependabot.yml
Dependabot creates a PR for us so we have to introduce a new action which updates node-modules for us.
> .github: add dependabot integration

- .github/dependabot.yml
- .github/workflows/dependabot.yml
Dependabot sets labels after PR creation so our pull requests tests would run regardless which is a waste of resources.
> .github: set `[no-test]` prefix for dependabot PR's

- test/check-application
Current Debian testing got a new podman version which changed the error message when `criu` is not available, to "failed to check for criu version: "criu": executable file not found in $PATH".
This is a bit less nice than the previous version requirement, but still clear enough, so accept it.
---
This blocks the [debian-testing refresh](https://github.com/cockpit-project/bots/pull/5358). see the [failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5358-20231009-162657-bc35b231-debian-testing-cockpit-project-cockpit-podman/log.html). I'll trigger an extra run against that new image here.
> test: Accept different criu test failure error message

- src/app.jsx
We previously didn't react to `health_status` events as they were broken, and only reacted to `exec_died` instead. With the upcoming podman release, `health_status` events are reliable, and they will also not be accompanied by an `exec_died` event any more. So start updating the container status on them.
Still keep listening to `exec_died` to support older podman releases.
Fixes #1443
> React to health_status events

- test/check-application
For some reason, .focus() sometimes does not take effect, and the element immediately loses the focus again. This causes set_input_text() to select the whole page text instead of the input element, and failing to set the intended value.
----
This fixes [this common flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1324-20230706-080945-2272c7a4-fedora-38/log.html#36), [another example](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1324-20230714-145100-6a267367-arch/log.html). So far this breaks pretty much every PR which runs tests three times (affected).
I realize this is a rather lame workaround, not a true fix. I investigated that in https://github.com/cockpit-project/cockpit-podman/pull/1324#issuecomment-1623250094 and attempted a better fix, but it didn't work, and …
> test: Add hack to avoid losing focus on #containers-filter

- src/Containers.jsx
- src/ImageRunModal.jsx
Large images which take some time download already shown the tabs but clicking on it would result in a JavaScript error as the Container object would not yet be available.
Closes:  #1408
> Don't crash when image is being downloaded and integration/console tab is clicked

- Makefile
- package.json
- src/Env.jsx
- src/ImageRunModal.jsx
- src/PublishPort.jsx
- src/Volume.jsx
- src/client.js
- src/util.js
- test/check-application
Fixes #609 
This introduces both dynamic validation run with "onBlur" and static validation when form is submitted:
[Screencast from 2023-07-13 13-16-41.webm](https://github.com/cockpit-project/cockpit-podman/assets/42733240/a164c43e-ef94-4077-99a6-7c6c400d12f8)
[Screencast from 2023-07-13 13-17-47.webm](https://github.com/cockpit-project/cockpit-podman/assets/42733240/0ee03ddc-21bd-4978-912b-5862dd50611f)
> Introduce field validation to Create container dialog

- .stylelintrc.json
- package.json
- src/ContainerTerminal.css
- src/Containers.scss
- src/ImageRunModal.scss
- src/ImageSearchModal.css
- src/Images.css
- src/podman.scss
Auto-fix usage of logical properties. This should help out with RTL as otherwise properties need to be changed from for example padding-left to padding-right.
Same rules are enabled in [Cockpit](https://github.com/cockpit-project/cockpit/pull/18777) but podman does not have RTL testing / pixel tests yet
> package.json: stylelint: Add logical property checker

- Makefile
- test/check-application
Until very recently, a cycle of `podman push`/`pull` preserved an
image's ID. Starting with containers-common 1-98 this is not the case
any more, as that changed the on-disk compression format. Quoting podman
devs: "The digests validate a specific image _representation_, not some
abstract "sameness" of an image."
Instead, remove the original busybox image for the user as well (that
already happend for the system user), and more explicitly check deletion
of an image with multiple tags.
Fixes https://github.com/containers/podman/issues/20611
Obsoletes https://github.com/cockpit-project/bots/issues/5515
> test: Drop push/pull ID preservation assumption

- src/PodCreateModal.jsx
- test/check-application
Recently the Image Create modal implemented validation for Volume/Port mapping. Re-use the same changes in Podman except for Volumes as there can be some improvements done there.
I'm happy to integrate the volume validation after https://github.com/cockpit-project/cockpit-podman/pull/1481
> Add create pod validation for name/port mapping

- test/check-application
Wait until creating a container with the intermediate image actually finished and succeeded before removing the image. Otherwise pulling the image away under the creation dialog's feet may fail the creation.
-----
Happened in https://github.com/containers/podman/pull/21007 in [this run](https://artifacts.dev.testing-farm.io/2a197701-88e6-4b4b-924f-47d265e43744/)
> test: Fix race condition with deleting busy intermediate image

- test/check-application
Since https://github.com/cockpit-project/cockpit/commit/1a903b480a0 each table row (health check entry) gets its own `<tbody>`
Also fix the bogus nth-child index in the initial "passed health run" check -- we expect exactly one run there.
Strengthen the "trigger run manually" checks -- ensure that this second run also gets a green badge and that there isn't a third run.
----
This [fails rather often on TF](https://artifacts.dev.testing-farm.io/291ce325-18af-41ac-9f2a-345fc254f1f4/), last seen in https://github.com/containers/podman/pull/21226
> test: Fix testHealthcheck table queries

- test/vm.install
These bugs are fixed in current Ubuntu releases.
----
I tested that manually. But also, our Debian/Ubuntu images already have tuned disabled.
> test: Drop tuned hack

- src/Containers.jsx
https://github.com/containers/podman/pull/21388 drops the `State.Health` field for containers without health checks. This causes an `undefined` crash in the container sort function.
---
I reproduced the crash with https://dashboard.packit.dev/results/copr-builds/1287492 and validated it against that build.
> Don't assume `State.Health` always exists

- test/browser/browser.sh
Commit 5ab52df9dd4 was not sufficient: The problem wasn't the tag repository, but that current Fedora rawhide has a 83-3 rebuild of cockpit-podman which is formally newer than our `83-1.<git stamp>` revisions from our main-builds COPR.
If the env has a main-builds COPR (for reverse dependency tests), we always want to install the latest version from that. So give it the highest priority (uninutitively, lower priority wins), and use `distro-sync` to up- or downgrade the package as necessary, and consider *only* the COPR.
Similar to https://github.com/cockpit-project/cockpit/commit/7ab102a551
----
This fixes failures like in https://github.com/containers/podman/pull/21388
I tested this in a fedora rawhide container, and it works fine:
```
Last metadata expiration check: 0:02:37 ago on Wed …
```
> fmf: Fix installation of our main-builds COPR

- test/check-application
We want to know when they actually fail -- ignoring that may corrupt the VM and break the next test.
> test: Expect `podman rm --all` to work

- test/check-application
https://github.com/containers/podman/pull/21601 changes the output for "bind port to all addresses" from "" to "0.0.0.0". Adjust the test to accept either format.
---
I tested this against the COPR of https://github.com/containers/podman/pull/21601 and the test passes now.
> test: Adjust for `podman inspect` change for "all addresses"

- .github/workflows/release.yml
- packit.yaml
The unit-tests container was dropped in
https://github.com/cockpit-project/cockpit/commit/f16f1fc14b88c
Cherry-picked from https://github.com/cockpit-project/starter-kit/commit/6e1427493a
> workflows: Switch release to cockpit/tasks container; packit: Release to Fedora 40

- test/check-application
The new pasta version [1] changes the "address already in use" error message to start with an upper case 'A'. Allow that as well.
[1] https://github.com/containers/podman/pull/21563
> test: Relax expected error message

- test/check-application
Should help with failures like [this](https://artifacts.dev.testing-farm.io/627b8e43-5f73-40b0-9602-cca726cef6cc/) and [this](https://artifacts.dev.testing-farm.io/14c22a81-bc43-452f-8a00-69415b8f69c3/)
> test: data dir backup/restore robustification

- test/check-application
With current pasta, it now looks like this:
```
Container failed to be started: Internal Server Error: pasta failed with exit code 1:
No routable interface for IPv6: IPv6 is disabled
Failed to bind port 5000 (Address already in use) for option '-t 5000-5000:5000-5000', exiting
```
We are not overly concerned with the exact message, as long as it says something about the confliting port 5000.
Follow-up to commit 1a6ccd8d4a
---
See https://github.com/containers/podman/pull/21563#issuecomment-1966591889
> test: Relax expected browser message for port conflict, too

- src/ImageRunModal.scss
This class is still called `pf-m-loading` in PatternFly v5 and still suffers from 6383. As the component is deprecated we should consider moving away from it.
> pf-v5-m-loading does not exists

- test/check-application
This assertion should no longer appear since Cockpit 260.
---
If this is good to go, we should also clean up machines.
> test: drop allowing cockpit-ws assertion

- test/check-application
The error is sent in multiple lines and looks like this:
```
error: Container failed to be started: Internal Server Error: pasta failed with exit code 1:
No routable interface for IPv6: IPv6 is disabled
Failed to bind port 5000 (Address already in use) for option '-t 5000-5000:5000-5000', exiting
```
---
see https://github.com/containers/podman/pull/21563#issuecomment-1971649911
> test: Adjust for new podman pasta version

- test/check-application
`podman system reset` defaults to waiting for 10s for containers to shut down, which unnecessarily slows down tests (see
https://github.com/containers/podman/issues/21874). To work around this, force-stop all containers first with a zero timeout.
---
Landing some parts of #1592 separately.
> test: Make system container cleanup faster

- test/browser/browser.sh
- test/check-application
- test/vm.install
The `restore_dir()` for podman's data directory is highly problematic:
This interferes with btrfs subvolumes and overlayfs mounts, and often
causes `cp` failures like
```
cp: cannot stat '/home/admin/.local/share/containers/storage/overlay/compat3876082856': No such file or directory
```
So move to `podman system reset`, and restore the test images
with `podman load` for each test.
Unfortunately `podman system reset` defaults to the 10 s wait timeout
(https://github.com/containers/podman/issues/21874), so we still need
the separate `rm --time 0` hack. But conceptually that can go away once
that bug is fixed.
This approach would also be nice on the system podman side, but it is super
hard to get right there especially on CoreOS: There we simultaneously want a
thorough cleanup, but also …
> test: Move from `restore_dir()` to `podman system reset` for user

- Makefile
The introduction of pasta [1] regressed user containers if there is no default route [2]. While that is being sorted out, add a fake interface with a default route for our offline tests, to unbreak upstream podman COPR testing.
[1] https://github.com/containers/podman/pull/21563
[2] https://github.com/containers/podman/issues/21896
> test: HACK: Add fake default route for podman-next scenario

- Makefile
podman 5 has landed in Fedora >= 40, so our tests start failing due to https://github.com/containers/podman/issues/21896
Extend the hack from commit cecb2cc6e8f24 to apply to all our images, not just the podman-next scenario.
----
Blocks https://github.com/cockpit-project/bots/pull/6050 . I'll trigger an extra test run against that. That does work, but it mis-reports the result as [fedora-40](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1608-5d3f1302-20240311-075730-fedora-40/log.html). See pilot board.
> test: Always add pasta default route hack

- pyproject.toml
These aren't unused, but discovered/enumerated by `unittest` or `pytest`.
---
Fixes [this static-code failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6048-20240311-121551-77e2f887-ubuntu-stable-cockpit-project-cockpit-podman/log.html) after we added vulture to the tasks container.
> lint: Ignore test functions in vulture

- test/check-application
The click and wait_in_text function already call wait_visible so we end up waiting twice.
> test: avoid a double wait_visible

- src/ImageRunModal.jsx
- test/check-application
The dynamiclistform only grows and removes entries by setting them to undefined which we need to account for. Previously this would map() and return [undefined, obj] but that raises an exception when you call Object.keys(undefined).
Fixes #1619
> Handle undefined state entries

- test/check-application
podman inspect seems to fail randomly when we just created a container, likely because it is still "setting up". As we try to work around the issue where we click too fast on the "create container" button while the dialog is still tearing down, we aren't too interested in much of podman inspect more in if the container is running.
> test: wait on the dialog to close 

- test/browser/browser.sh
- test/browser/main.fmf
- test/browser/run-test.sh
- test/vm.install
This simplifies the "outside" setup quite a bit and gives us the same tasks container that test runs on the Cockpit CI run under.
> test/browser: run tests inside the tasks container

- packaging/cockpit-podman.spec.in
In order to support testing on opensuse's tumbleweed image, the spec file needs to be updated to support it.
> spec: Support SUSE specific BuildRequires

- test/check-application
https://github.com/containers/podman/pull/22322 changes the reported default restart policy from "" to "no". Accept both forms for the time being, until all supported OSes have podman ≥ 5.1.
----
See https://github.com/containers/podman/pull/22322
@mheon FYI
> test: Adjust expected default RestartPolicy value

- test/check-application
podman 5.1 [1], by way of [2], adds a "StartInterval" element to the `.Config.Healthcheck` API field. This is an API breakage, but accept either form until 5.1 is available on all OSes.
[1] https://github.com/containers/podman/pull/22334
[2] https://github.com/containers/image/commit/b6afa8ca7b324aca8fd5a7b5b206fc05c0c04874
> test: Adjust expected HealthCheck API format

- src/ContainerIntegration.jsx
- src/Containers.jsx
- test/check-application
On some systems a toolbox container has an intermediate image as image which since 17d258855fac34556d66337f9015d47741dd482c is no longer passed to the renderRow.
Closes #1649
---
I am unsure how I got into this situation or how to reproduce it. But it is :100: valid for a container to depend on an intermediate image and it should not crash the page.
> Pass all local images for container integration details

- test/browser/run-test.sh
Our c10s CI image is called "centos-10" without the -stream suffix. This fits better with `os-release` and makes the names shorter. Adjust the building of `$TEST_OS` accordingly.
[1] https://github.com/cockpit-project/bots/pull/6218
----
Note that I can't enable c10s testing on c-podman just yet, the initial blocker is https://issues.redhat.com/browse/RHEL-32905 (which is impossible to work around). So let's just cherry-pick https://github.com/cockpit-project/starter-kit/pull/839 for the time being, so that I won't forget.
> fmf: Restrict "-stream" TEST_OS suffix to CentOS 8/9

- .flake8
- pyproject.toml
- test/check-application
Ruff's preview rules now implements the rules which we used flake8 for.
> test: enable ruff preview rules

- .eslintrc.json
- src/Images.jsx
This rule is not part of the standard ESLint recommends set but is useful and can be auto-fixed.
> eslint: enable no-useless-fragment rule by default

- src/Containers.jsx
- src/podman.scss
- src/util.js
- test/check-application
The previous view like "0.001/16 GB" was not very helpful. For containers
without an explicit memory limit, the denominator `containerStats.MemLimit` is
the *host* memory, not something specific to the container. This makes it hard
to see which containers actually have a configured limit. For containers which
*do* have a memory limit, the numerator applied to that, but that makes it
difficult to compare to other containers and its relative size on the host
(from the "see the forest, not the tree" perspective).
Rework this to show Memory in three parts:
- The first line shows the container's memory usage as a percentage of
the host's memory. That makes them comparable and gives a good
feeling about host resource utilization, similar to the CPU usage
view.
- The second line shows the …
> Rework display of current container memory usage

- test/check-application
We pulled in https://github.com/cockpit-project/cockpit/pull/20356 now, so we don't expect "KB" any more.
> test: Tighten expected unit for kilobyte

- HACKING.md
- packit.yaml
- test/browser/run-test.sh
- test/check-application
C8S is going to be EOL in a month [1], and we are not going to do a RHEL 8 update at this point any more.
Keep testing on rhel-8-10 though, as we do want to keep the code working for the beiboot scenario or backports.
[1] https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/
---
En passant this also sweeps the recent [c8s regression](https://artifacts.dev.testing-farm.io/25066bae-7ddb-4bd3-a254-2693f15dfb68/) under the rug which we've been ignoring for a while. So c-podman tests should go green again now.
> packit: Drop testing on CentOS 8 Stream

- test/run
When a system container runs a user container cannot be created as it exits with a pasta error.
Reported as https://bugzilla.redhat.com/show_bug.cgi?id=2277954
> Makefile: workaround pasta user containers being broken

- test/check-application
podman 5.0.2 in CentOS 9 stream changes the error message for port conflicts from "address already in use" to "failed to bind any port". Accept that as well.
---
In the last half day, all podman PRs started to fail on c9s [like this](https://artifacts.dev.testing-farm.io/fe31fb3f-f757-48a2-a90d-4fdde5d02294/). This reproduces locally with upgrading podman from https://kojihub.stream.rdu2.redhat.com/koji/buildinfo?buildID=61248 (it's not yet in a CentOS 9 stream compose).
> test: Adjust expected error message for port conflict to podman 5.0.2

- packaging/cockpit-podman.spec.in
- test/check-application
- test/vm.install
Fix tests to support testing on tumbleweed. Sorry that this took a while. Got quite stuck on the cgroups issue for while :-)
This depends on: https://github.com/cockpit-project/bots/pull/6450
> Fix tests for opensuse tumbleweed

- packit.yaml
- test/browser/main.fmf
https://issues.redhat.com/browse/RHEL-34650 finally got fixed, so podman works in CentOS/RHEL 10 now.
> packit: Enable centos-stream-10

- src/ContainerTerminal.jsx
There's no reason to use that Cockpit API, and we want to deprecate it.
> Replace cockpit.utf8_{de,en}coder with standard JS API

- Makefile
- test/check-application
See https://github.com/cockpit-project/cockpit/pull/20563
> test: Adjust to changed key input testlib API

- src/Images.jsx
- test/check-application
This PR implements a 'Pull' option for existing images. This action is added in the dropdown menu for an image. In addition to this, it includes a 'Pull all images' option at the top level to pull all images in storage. The goal is to easily allow updating containers when using tags like 'latest' or a just major version number.
The implementation makes use of the existing downloadImage function that is used when downloading a new image. It was slightly modified to support multiple images being downloaded simultaneously.
I'm not familiar with the localization mechanism used in Cockpit, but in line with other strings I wrapped the labels in `_("Label")`. Upon changing the display language this (somewhat obviously) didn't automatically work, so translations will need to be added.
---
The new …
> Implement pull option for existing images

- src/client.js
Hey! If a container provided no environment variables itself it would crash the frontend of cockpit whenever you clicked into the integrations tab on the running container. Podman's api wasn't providing config.env in these cases which led to it being undefined, this is just a small change to make sure it's always set to an array
> Handle cases where the image provides no env

- src/ContainerDetails.jsx
- src/ContainerHealthLogs.jsx
- src/ImageHistory.jsx
- src/Images.jsx
- src/PruneUnusedContainersModal.jsx
- src/util.js
- test/check-application
We want to drop the date-fns runtime dependency, and already did so in all other projects. For consistency, show all dates (such as container creation, health checks, or image history) as relative times via `timeformat.distanceToNow()`, with a tooltip that shows the precise absolute time. This is similar to what we did in machines [1].
Introduce a `RelativeTime` helper component for that, and teach it to accept both ISO-formatted strings as well as raw timestamps to get rid of a few repeated `Date.parse()` calls. Also, most time stamps that we get are in ms (just like `Date` itself), so make it accept that instead of seconds.
[1] https://github.com/cockpit-project/cockpit-machines/commit/b63a54e6721
> Show all dates/times as relative

- package.json
- src/util.js
Latest cockpit lib moved `timeformata.distanceToNow()` away from date-fns. Drop the obsolete `addSuffix` argument, and drop the now unused date-fns npm dependency.
> Adjust to current Cockpit timeformat API, drop date-fns

- test/browser/browser.sh
See https://issues.redhat.com/browse/RHEL-49567 for details.
----
This fixes the centos-10 TF failure which started to happen recently: https://artifacts.dev.testing-farm.io/a3c1d682-18fc-4d6e-9b63-ee97c291e058/
> fmf: Disable SELinux for version which breaks nspawn

- src/Images.jsx
The state of this was never initialised.
> Initialise `showPruneUnusedImagesModal` state

- src/ImageRunModal.jsx
- test/check-application
Fixes bug that makes it impossible to search containers with full URL such as `docker.io/{user}/{container_name}`.
> Fix searching containers with full URL

- Makefile
passt got fixed in [1] to get along with multiple network interfaces and no default routes.
[1] https://bodhi.fedoraproject.org/updates/FEDORA-2024-4632bfa865
[2] https://bugzilla.redhat.com/show_bug.cgi?id=2277954
----
This should only work in updates-testing scenario today. This will take some time to propagate to Fedora, CentOS 10 etc., and there's no hurry to land this -- I mostly just want to validate the bodhi update. [Last night's run](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-c775d715-20240626-015919-fedora-40-updates-testing/log.html) was against that version and passed, now let's try this without the hack.
> test: Drop dummy interface

- test/browser/browser.sh
The current version selinux-policy-40.13.6-1.el10.noarch *still* breaks machined. This was a courtesy, but I'm not playing this game for longer than necessary. Just disable SELinux in general until we get notified that the bug gets fixed.
----
I notified/re-opened https://issues.redhat.com/browse/RHEL-49567 . Fixes this failure: https://artifacts.dev.testing-farm.io/5c511379-43b6-4c6b-86aa-3a6a7a312db6/
> fmf: Disable SELinux for all of RHEL 10

- Makefile
- package.json
- test/browser/run-test.sh
See https://github.com/cockpit-project/cockpit/pull/20832
Drop chrome-remote-interface NPM dependency.
Explicitly add a "glob" devDependency to follow suit with
https://github.com/cockpit-project/cockpit/commit/680decc155a
It was previously used implicitly through a transient dependency of
something else, but our esbuild po-plugin uses it explicitly.
Also sort package.json properly (done by `npm install --save-dev`).
> test: Move from CDP to BiDi

- test/check-application
Test checks if a warning is displayed therefore create button should be disabled.
https://cockpit-logs.us-east-1.linodeobjects.com/pull-1821-bfa093ee-20240819-082934-debian-testing/log.html#10-2
> fix disabled button check

- test/check-application
Split out from #1832.
I'll trigger an extra /firefox run.
> Some test fixes

- src/Env.jsx
- test/check-application
The `companionField` in handleEnvValue() is meant to be the *other* (key/value) field. It doesn't make sense to specify its own value, that just looked like a copy&paste error from the *-key input handler.
With that you can type "FOO=bar" and get the automatic split. The test "cheated" with `set_val()` which sets all letters atomically. Test "RHUBARB=STRAWBERRY" separately with proper keyboard input.
Splitting muliple variables can only work with an atomic value setting, i.e. the user doing copy&paste. Keep the `set_val()` bit and explain it, and also validate that the fields get created and split as expected.
---
Spotted as part of #1832. It may help with the [testRunImageUser failure](https://artifacts.dev.testing-farm.io/3a44f391-ea98-46b4-b63f-9bb8d565c2ea/), but it's …
> Fix magic env var value auto-splitting

- src/ContainerIntegration.jsx
- test/check-application
This PR allows rendering podman container ports  as  ranges.
It makes sure to only render a range if the range of ports has the same protocol and IP and the host ports are an equivalent range.
This is my first PR in javascript, so please let me know if anything needs fixed!
Closes #1378 
Examples:
> [feat] render podman container/pod ports as ranges

- test/browser/browser.sh
Without iptables-nft `podman container checkpoint --tcp-established` fails as `iptables-restore` is missing.
> test: workaround missing iptables-nft required for criu

- src/ImageRunModal.jsx
- test/check-application
Pressing "Enter" in the dialog on any active form element (such as the search input or the checkboxes) previously bubbled up to the Form, which then activated the first popover help. This is unexpected and very irritating especially when using the search input.
Just ignore the Enter key to fix that, similar to what the image search modal already does.
See https://github.com/cockpit-project/cockpit-podman/pull/1821#issuecomment-2374302608
> Fix irritating Enter key behaviour in container creation dialog

- src/ImageRunModal.jsx
- test/browser/main.fmf
- test/check-application
fixes: #1220
Add support to pull images from registries which do not support search API.
https://issues.redhat.com/browse/COCKPIT-1148
> fix searching on non-searchable image registries

- Makefile
- org.cockpit_project.podman.metainfo.xml
- packaging/debian/control
Rename the file to match its ID, add developer/home page, and extend the
description. This fixes all issues with `appstreamcli validate`:
> W: org.cockpit_project.podman: url-homepage-missing
> W: org.cockpit_project.podman: metainfo-filename-cid-mismatch
> I: org.cockpit_project.podman:38: description-first-para-too-short
> I: org.cockpit_project.podman: developer-info-missing
---
See https://appstream.debian.org/sid/main/issues/cockpit-podman.html . `metainfo-filename-cid-mismatch` is new with the recent update of AppStream to 1.0.3 in Debian. See also https://github.com/cockpit-project/cockpit/pull/21103
> appstream: Fix validation problems

- src/Env.jsx
- test/check-application
Validate env var keys with regex. Remove Required asterisk for value. This might sound weird but Podman and shells in general allow setting env vars without values.
Fixes: https://github.com/cockpit-project/cockpit-podman/issues/1622
> Validate environment variables

- test/check-application
Occasionally, `crun checkpoint` fails in Fedora 41 podman upstream PRs (in revdeps tests). This isn't otherwise reproducible,  so start with collecting all information. The journal just says "Please check CRIU logfile", so let's collect that.
----
See https://github.com/containers/podman/pull/24238#issuecomment-2410863519 . I've seen this fail several  times in the last week.
> test: Attach criu dump log on checkpoint failures

- test/browser/browser.sh
See https://bugzilla.redhat.com/show_bug.cgi?id=2319310
---
This should hopefully put an end to the occasional [checkpoint/restore failures](https://artifacts.dev.testing-farm.io/cae003c8-50ff-4261-821e-0e8d7ddfff8b/) in upstream podman F41 PRs such as https://github.com/containers/podman/pull/24300 or https://github.com/containers/podman/pull/24238#issuecomment-2417049948
> fmf: Explicitly install iptables-nft for Fedora 41 as well

- plans/all.fmf
https://issues.redhat.com/browse/TFT-2564 roars its ugly head again and completely breaks installation due to installing Fedora packages on CentOS 10.
See https://github.com/containers/podman/pull/24255
Same solution as https://github.com/cockpit-project/cockpit-machines/commit/41f337fd85b85
> tmt: Disable fedora repo for C10 tests

- src/PodCreateModal.jsx
- test/check-application
I have found four issues:
- Validation results would not always make it into the UI while typing into the fields. This was confusing, but hitting "Create" would always straighten things out.
- Removing port rows and then hitting "Create" while something was invalid would shift the (genuine) validation errors into the places of the previous removed ports. There they would invisbly keep the "Create" button from ever getting enabled again.
- `<TextInput type="number" />` does not usefully distinguish between empty strings and strings that are not numbers, and it sends fewer change notifications than expected. For example, starting to type random letters into a previously empty field will produce no change events and we get no opportunity to run our validation code.
- The Volumes are not …
> pods: Fix PodCreateModal validation issues

- src/ImageRunModal.jsx
This is the same fix as in 07197e5 for PodCreateModal.
> containers: Always ignore validation errors for empty slots in ImageRunModal

- test/vm.install
In https://github.com/cockpit-project/bots/pull/7046 we want to pre-install the cockpit/ws container to the fedora-40 image (and in the future, whichever Fedora version the container is based on). This "breaks" pixel tests due to the additional container image, so remove it for anything except OSTree images.
We don't just want to include it in the pixel tests, as the container's base image and pixel reference OS move independently.
> test: Remove cockpit/ws container on non-OSTree images

- package.json
See https://github.com/cockpit-project/cockpit/issues/21151 We already configured this in dependabot (commit fac7a3824b), but that landed too late, after the dependabot run.
> package.json: downgrade sass back to 1.79.6

- test/check-application
testDownloadImage flaked a very often as the test succeeds when runs fast enough. Tagging an image to a new name in this case changes the image list name to `copybox` possibly because it is sorted before `my-busybox`.
---
Alternatively we can wait on either?
> test: wait on new image tag

- src/Containers.jsx
- src/util.js
String.prototype.substr() is a deprecated API.
---
Couldn't find an eslint rule for this, so we'll have to pay attention.
> Convert substr() usage to substring()

- test/browser/browser.sh
CentOS 10 is currently broken with:
Error: building local pause image: finding pause binary: exec: "catatonit": executable file not found in $PATH
So check if the package is installed.
---
Can already locally reproduce the issue but this seems useful regardless
> test: show catatonit version for testing farm runs

- test/check-application
Use our setupRegistry() helper.
> test: Factorize registry setup in testDownloadImage()

- test/vm.install
RHEL 10 started to break `podman -p` port forwarding to localhost by default [1]. This was a deliberate change [2][3]. We really don't care about firewalling localhost ports from containers (does anybody really?), so revert back to the previous behaviour (which is still the default on Fedora) of having StrictForwardPorts=no.
This obsoletes our naughty https://github.com/cockpit-project/bots/issues/7291
[1] https://issues.redhat.com/browse/RHEL-72937
[2] https://firewalld.org/2024/11/strict-forward-ports
[3] https://github.com/firewalld/firewalld/issues/1380
---
This should make the [four skipped tests](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1951-68a71ea4-20250107-150223-rhel-10-0/log.html) green again. After this lands, I'll send a bots PR to drop the naughty.
> test: Disable firewalld StrictForwardPorts on RHEL 10

- src/ImageRunModal.jsx
- test/check-application
> Use TypeaheadSelect in ImageRunModal

- src/Containers.jsx
- src/podman.scss
- test/check-application
Small steps into better supporting quadlets in cockpit-podman.
The visual changes are a new `service` label to identify quadlet/podman generate systemd managed containers
Other changes are:
* Removing "run healthcheck from the container kebabmenu". This can be done in the details view of a container and doesn't need to be such a prominent feature
* Hide the rename option for quadet/systemd containers, this likely causes issues as the `.container` file determines the name of the container allow users to change it will cause issues.
> First steps of quadlet integration

- src/ContainerLogs.jsx
- src/ContainerTerminal.jsx
- src/Containers.jsx
- src/app.jsx
Fixups that I split out from #1976.
See [this log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1976-80759695-20250124-114135-fedora-41/log.html#37) for the `dimensions` crash:
> error: TypeError: Cannot read properties of undefined (reading 'dimensions')
> Add screenReaderText, Fix XTerm.js crash, Improve console log messages

- src/app.jsx
- test/browser/browser.sh
- test/check-application
Always start the system and user `podman.socket` unit on initialization. There really is no reason to explicitly ask the user about it -- we can treat it as "extended cockpit" to just access podman.
There also isn't a reason to enable the socket unit -- starting it on demand is fine from cockpit-podman's perspective.
Now the user will only see the empty state if the service fails, which should be very rare. So turn the Troubleshoot button into a primary one.
We also don't need the "System/User podman is also available" alerts any more -- gaining root privileges auto-starts the system service.
-----
This is a necessary prerequisite for https://issues.redhat.com/browse/COCKPIT-1086 , but useful in its own right -- it removes a big hurdle/annoyance at startup.
If the system or user's …
> Automatically start podman.socket

- test/check-application
The [new debian-testing](https://github.com/cockpit-project/bots/pull/7379) image now shows a different error, to avoid line limits convert it to a list. In a follow up I intend to cleanup the errors a bit.
> test: adjust to new CRIU unsupported error from podman

- test/vm.install
The default policy change in RHEL 10 got reverted, see https://issues.redhat.com/browse/RHEL-72937
This reverts commit f1469ec566fdfdbcd7afc0f639c1b164d8ff7ecb.
> Revert "test: Disable firewalld StrictForwardPorts on RHEL 10"

- src/app.jsx
- test/check-application
This covers the `streamEvents` plus explicit channel watching in
app.jsx. We can use this to guard when to remove the extra
`cockpit.channel()` `close` watching, which is not necessary with the
Python bridge, but still relevant on the C bridge (Debian 12 and RHEL 8).
> test: Check podman socket going away while cockpit session is running

- packit.yaml
The cloud images are missing [1] and not even COPR works. Also move the aarch64 test from -latest (which is 42 now, which doesn't work) to -latest-stable (which is 41).
"-development" also triggers -42, so avoid the alias and explicitly say "rawhide".
[1] https://pagure.io/fedora-infrastructure/issue/12389
----
Similar to https://github.com/cockpit-project/cockpit/pull/21591 , same rant applies.
Once this lands, I'll apply it to machines and files (ostree is fine).
> packit: Drop copr_build job redundancy, re-disable Fedora 42

- .cockpit-ci/container
This causes weird failures in testFailingPodmanService with Firefox 135, see #1999. This breaks too many podman upstream PRs (which run cockpit-podman reverse dependency tests).
This reverts commit 8f78a848de6c49612t 947559fbd46893c1d72141d.
---
Let's land that and then investigate #1999 with less time pressure.
> Revert "cockpit-ci: Update container to 2025-02-08"

- src/Containers.jsx
Not showing the container actions causes the downloading container row to not fully extend so instead disable the container actions so the columns stay the same.
Closes: #1862
---
> Disable container actions when downloading

- src/ContainerCheckpointModal.jsx
- src/ContainerCommitModal.jsx
- src/ContainerDeleteModal.jsx
- src/ContainerHeader.jsx
- src/ContainerHealthLogs.jsx
- src/ContainerLogs.jsx
- src/ContainerRenameModal.jsx
- src/ContainerRestoreModal.jsx
- src/ContainerTerminal.jsx
- src/Containers.jsx
- src/ImageDeleteModal.jsx
- src/ImageHistory.jsx
- src/ImageRunModal.jsx
- src/ImageSearchModal.jsx
- src/Images.jsx
- src/PodActions.jsx
- src/PodCreateModal.jsx
- src/PruneUnusedContainersModal.jsx
- src/PruneUnusedImagesModal.jsx
- src/app.jsx
- src/client.js
- src/rest.js
- src/util.js
- test/check-application
Preparation and heavy lifting for https://issues.redhat.com/browse/COCKPIT-1086 . But this PR does not yet change visible behaviour and (almost) no pixels.
I have a proof of concept hack that can switch to another user with http://127.0.0.2:9091/podman#/?owner=1002 : 
This will need some design discussions though, and of course some more code and test work. But this became both big enough that a review is prudent now, and I am also reasonably convinced that we can make this work.
> Generalize code for multiple users

- src/Images.jsx
- test/check-application
The test was cheating: It carefully removed all localhost/* images before "pull
all images". But that is a realistic situation -- anyone using any pod will at
least have a `localhost/pause` image.
It also does not make sense to use `utils.image_name()` for an API call -- this
is a human UI formatter, `<none>:<none>` is nonsensical for an image pull
request.
Fix onPullAllImages() to weed out tag-less and localhost/* only images, and
cover both cases in the tests.
Fixes #2025
> Ignore localhost registry and untagged images in "Pull all images"

- src/ContainerCheckpointModal.jsx
- src/ContainerCommitModal.jsx
- src/ContainerDeleteModal.jsx
- src/ContainerHealthLogs.jsx
- src/ContainerRenameModal.jsx
- src/ContainerRestoreModal.jsx
- src/ContainerTerminal.jsx
- src/Containers.jsx
- src/ImageDeleteModal.jsx
- src/ImageHistory.jsx
- src/ImageRunModal.jsx
- src/ImageSearchModal.jsx
- src/Images.jsx
- src/PodActions.jsx
- src/PodCreateModal.jsx
- src/PruneUnusedContainersModal.jsx
- src/PruneUnusedImagesModal.jsx
- src/app.jsx
- src/client.js
- src/rest.js
- test/check-application
Keep the `connection` and underlying `cockpit.http()` object for each user, and change the client.js API to take a connection object instead of an uid.
With that we don't have to create a new HTTP connection for each request (thus more efficient), and gain the possibility to close a running monitor of a particular user (which will become important for multi-user support).
---
Part of https://issues.redhat.com/browse/COCKPIT-1086
> Move to connection object based API

- test/check-application
Since crun 1.20 via https://github.com/cockpit-project/bots/pull/7498
> test: The debian-testing image now can do checkpoint/restore

- src/ContainerLogs.jsx
- src/app.jsx
- src/client.js
- src/rest.js
- test/check-application
See my woes in https://github.com/cockpit-project/cockpit-podman/pull/2024#issuecomment-2705655132 . This is a problem on current main already. I started with reproducing this in a test, the first run should make sure it actually fails on all OSes as expected -- it does on commit 987ef61b, like [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-2038-987ef61b-20250307-075845-fedora-42/log.html). Only debian-stable and rhel-8-10 are passing (with the C bridge).
The current PR version also includes the fix.
I realize this is rather odd. I put it onto my TODO list to reproduce this issue in cockpit's unit tests and fix that bug properly. But I've been chasing this for three days, and it's not going to be easy with the existing https://docs.python.org/3/library/http.client.html based …
> Fix console junk and cockpit.http() streaming lock-ups

- src/ImageRunModal.jsx
- test/check-application
The dialog's Owner: radio button should default to the owner of the image that was selected to run, not statically to "system". In most cases you don't want to run a system container from a user image.
This scenario is not covered anywhere yet, and difficult to put into `testRunImage{User,System}`, so create a new `testRunImageUserWithAuth` test case for this.
> Fix "Run Image" dialog default owner

- test/check-application
Should help when we eventually need to move to PF6 and update all the selectors
> test: re-use `getContainerAction` helper

- src/Containers.jsx
"pod group" makes no sense. A pod is a group of containers, and this is a single pod, not a group of pods.
> Fix pod label

- src/Containers.jsx
- src/PodActions.jsx
- src/podman.scss
- test/check-application
- test/vm.install
This PR removes all lifecycle actions as stopping a quadlet container/pod or restarting (and having it fail) leads to the container/pod going away unexpectedly. That is because showing stopped/failed quadlets involves more work.
Pod group is now shown as `pod service group`. (**outdated**)
Open discussion topic is if this should wait on a link to the service page where users can easily stop/restart their container/pods?
> Quadlet support v2

- test/vm.install
CentOS 9's bootc image no longer exposes `OSTREE_VERSION` in /etc/os-release. Likely due to Fedora CoreOS moving from ostree to composefs. As every image we test is moving to bootc the check whether cockpit-ws should be kept can be simplified to seeing if we booted into a bootc system.
> test: generalise bootc check

- pyproject.toml
- test/check-application
This makes the admin setup independent from root's, and is easier.
---
See https://github.com/cockpit-project/cockpit-podman/pull/2024/files#r2010660027
Our bots images are already set up that way, but [it is required on TF](https://artifacts.dev.testing-farm.io/f22e32ed-1fde-469f-93c6-2efdddefa4d6/)
> test: Robustify admin user SSH key setup

- src/Containers.jsx
- src/app.jsx
- src/rest.js
- test/check-application
When the session has superuser capabilities, scan the system for all users
which have some podman containers running (via cgroupfs heuristics) and add
them to the owner selector.
Teach `rest.getAddress()` and the podman.socket startup to connect to the
podman service of an arbitrary UID by assuming that their runtime directory is
`/run/user/$UID`. This is a necessary, but safe enough assumption -- if the
system was modified to use a different one, then we won't support connecting to
that user.
However, we want to be careful and only connect to one extra user at a time: we
don't want connections to pile up (as the parallel events will eventually slow
down the page) or interfere with each other (as these users are isolated for a
reason). So only connect to the service once the user actually …
> Support connecting to other users

- src/PruneUnusedImagesModal.jsx
- test/check-application
The prune image dialog pixel tests didn't have both checkboxes checked which caused flakes in CI. The prune image dialog should always have both checkboxes checked by default.
See the failure https://cockpit-logs.us-east-1.linodeobjects.com/pull-2083-3f2bbde9-20250404-152013-fedora-41/log.html
> Update pixel tests

- src/Containers.scss
When there are no rows we show the EmptyState component and the Table wouldn't be rendered so `ct-table-empty` is never shown.
> Drop ct-table-empty css rule

- src/ContainerDetails.jsx
- test/check-application
Restart/Stop/Start support has been removed so users can't restart a container currently. With a link to the services page they can at least restart it without temporarily losing the container from the view.
---
> Show systemd service links for quadlets

- pyproject.toml
Our custom test shebang is not compatible with pyright so we have to like mypy teach it about bots/ our custom testlib.
> pyproject: set pyright extra import paths

- src/ImageRunModal.jsx
- test/check-application
When using a registry like `registry.opensuse.org` it would trim off `registry.` for the ui, then later on when it came to actually filtering the results it would also only select `images[opensuse.org]` which would never exist
> Use the fully qualified registry name in state

- .github/workflows/nightly.yml
- HACKING.md
- Makefile
- test/run
We can't currently test a Podman PR against a Cockpit PR easily, but as every Cockpit PR creates a Packit rpm build with a copr repository we can use this.
This is for example useful when debugging why clicking on a logs link from Podman throws an exception in the Cockpit logs page.
---
Been using a hack in here https://github.com/cockpit-project/cockpit-podman/pull/2120 but we can easily generalise this.
> test: allow testing against a Cockpit Packit copr

- src/ContainerLogs.jsx
- src/Containers.jsx
- test/check-application
Quadlets are services managed by systemd and detailed logs including service restarts can only be seen in journald's logs. This functionality is now limited to only system services as Cockpit's log page has no `--user` support.
Related: #2055
We should investigate supporting user journal support in Cockpit, of course we cannot support the other (non-logged in) users.
---
> Show link to logs page for quadlets

- src/ContainerDetails.jsx
- src/Containers.jsx
- src/util.js
A podman-compose container cannot be managed via systemd but still sets a label PODMAN_SYSTEMD_UNIT with `podman-compose@$project`.
Restarting such a unit isn't even possible with systemd:
systemctl restart podman-compose@root.service
Failed to restart podman-compose@root.service: Unit podman-compose@root.service not found
Closes: #2112
> Don't flag podman-compose containers as a service container

- src/client.js
We haven't updated this in years, and "1.12" as a version does not make sense. The intention as per Paul Holzinger [1] is to have a podman version there. The oldest one that we still support is 3.4.0 in Ubuntu 22.04 LTS.
[1] https://github.com/containers/podman/pull/24005#issuecomment-3058499967
> Bump podman API version to 3.4.0

- test/check-application
These old distro releases are deeply frozen, and this isn't a critical bug, so it won't ever be fixed. Just ignore the message at this point.
---
Fixes [this flake](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-2185-1d38402d-20250711-035640-rhel-8-10/log.html#1), [another example](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-2191-b84909e6-20250716-044707-rhel-8-10/log.html)
That reminds me, we should move rhel 8 testing to beiboot. We should stop supporting main on the C bridge, we won't upload current releases to RHEL 8 any more anyway.
> test: Ignore occasional old C bridge "should not be reached" message

- src/app.jsx
- src/client.js
Investigating [this flake](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit-podman&days=5&test=%2Ftest%2Fcheck-application+TestApplication.testOtherUsers), [example log](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-2187-c20c469a-20250714-032558-ubuntu-stable/log.html#23). Also observed on [rhel-8-10](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-7982-84490583-20250711-232323-rhel-8-10-cockpit-project-cockpit-podman/log.html).
The log seems pretty clear, and if podman keeps timing out there's not much that we can do about it:
> warn: init uid null getInfo failed: Error: timeout
> warn: init uid 0 getInfo failed: Error: timeout
> testOtherUsers timeout on ubuntu-stable

- Makefile
- test/browser/browser.sh
- test/check-application
- test/vm-beiboot.install
- test/vm-ws-package.install
- test/vm.install
Let's deprecate the "native rpm" rhel-8-10 scenario. We won't ever update RHEL 8 to the current upstream versions. Instead, let's make sure that RHEL 8 keeps working with recent cockpit/ws containers or the flatpak in beiboot mode.
Split off the rpm/beiboot specific bits of test image preparation into their own scripts.
---
> test: Add ws-container scenario

- test/browser/browser.sh
- test/vm.install
Stop assuming that the number is preceded by a space; it's a tab in RHEL 9. Just require a word boundary.
Also, with the most recent image refreshes, the `admin` user already doesn't have subuids, so we have to add them back as well.
---
Fixes https://github.com/cockpit-project/bots/pull/8042
> test: Fix subuid hack for RHEL

- build.js
When the build is cancelled in watch mode, `dist` might not exist so copying to it will always fail and show a long useless traceback. Unfortunately esbuild errors don't give much information so we can't match the exact cancelled error.
> build.js: don't copy assets when the build is cancelled

- test/check-application
This is mostly a noop, but helps in porting things over to eventually use `systemd-run` for admin session commands and figuring out what really needs to change.
> test: explicitly use m.execute() for system commands
